// web/src/views/LoginView.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "@/stores/auth";
import LogoIcon from "@/components/LogoIcon.vue";

const auth = useAuthStore();
const router = useRouter();
const email = ref("");
const password = ref("");
const error = ref("");

async function handleLogin() {
  error.value = "";
  try {
    await auth.login(email.value, password.value);
    router.push("/");
  } catch (err: any) {
    error.value = err.message ?? "Login failed";
  }
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-background p-4">
    <div class="w-full max-w-sm space-y-8">
      <!-- Logo -->
      <div class="text-center">
        <LogoIcon :size="56" class="mx-auto mb-4" />
        <h1 class="text-2xl font-bold bg-gradient-brand bg-clip-text text-transparent">
          IO
        </h1>
        <p class="text-sm text-muted-foreground mt-1">Sign in to your dashboard</p>
      </div>

      <!-- Form -->
      <form
        @submit.prevent="handleLogin"
        class="space-y-4 bg-card border border-border rounded-lg p-6"
      >
        <div>
          <label class="text-sm font-medium text-muted-foreground" for="email">Email</label>
          <input
            id="email"
            v-model="email"
            type="email"
            required
            class="mt-1 w-full rounded-md border border-border bg-input px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            placeholder="you@example.com"
          />
        </div>
        <div>
          <label class="text-sm font-medium text-muted-foreground" for="password">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            class="mt-1 w-full rounded-md border border-border bg-input px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            placeholder="••••••••"
          />
        </div>

        <div v-if="error" class="text-sm text-destructive">{{ error }}</div>

        <button
          type="submit"
          :disabled="auth.loading"
          class="btn-gradient w-full py-2.5"
        >
          {{ auth.loading ? "Signing in..." : "Sign In" }}
        </button>
      </form>

      <p class="text-center text-xs text-muted-foreground">
        Personal AI Assistant Daemon
      </p>
    </div>
  </div>
</template>

// web/src/views/LoginView.tsx
import { useState, type FormEvent } from "react";
import { useNavigate } from "react-router";
import { useAuthStore } from "@/stores/auth";
import { LogoIcon } from "@/components/LogoIcon";

export default function LoginView() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const login = useAuthStore((s) => s.login);
  const loading = useAuthStore((s) => s.loading);
  const navigate = useNavigate();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");
    try {
      await login(email, password);
      navigate("/");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Login failed");
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen">
      <form onSubmit={handleSubmit} className="w-full max-w-sm space-y-6 p-8 bg-card rounded-lg border border-border">
        <div className="flex flex-col items-center gap-2">
          <LogoIcon size={48} />
          <h1 className="text-2xl font-bold text-gradient-brand">Sign In</h1>
        </div>
        {error && <p className="text-sm text-destructive text-center">{error}</p>}
        <div className="space-y-4">
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email"
            required
            className="w-full px-3 py-2 bg-input border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          />
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password"
            required
            className="w-full px-3 py-2 bg-input border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          />
        </div>
        <button
          type="submit"
          disabled={loading}
          className="w-full py-2.5 rounded-md btn-gradient text-white font-medium disabled:opacity-50"
        >
          {loading ? "Signing in..." : "Sign In"}
        </button>
      </form>
    </div>
  );
}
