// packages/web/src/views/LoginView.tsx
import { IoMark } from '@/components/ui/io-mark';
import { useAuth } from '@/lib/auth';
import { useState } from 'react';

export function LoginView() {
	const { signIn } = useAuth();
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [error, setError] = useState<string | null>(null);
	const [loading, setLoading] = useState(false);

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError(null);
		setLoading(true);

		const { error: err } = await signIn(email, password);
		if (err) {
			setError(err);
		}
		setLoading(false);
	}

	return (
		<div className="min-h-screen bg-[#161616] flex items-center justify-center relative overflow-hidden">
			{/* Subtle dot grid */}
			<div
				className="absolute inset-0 opacity-[0.04]"
				style={{
					backgroundImage: 'radial-gradient(circle, #E43A9C 1px, transparent 1px)',
					backgroundSize: '32px 32px',
				}}
			/>
			{/* Glow behind logo */}
			<div
				className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-[60%] w-[400px] h-[300px] rounded-full blur-3xl pointer-events-none"
				style={{
					background: 'radial-gradient(ellipse, rgba(228,58,156,0.12) 0%, transparent 70%)',
				}}
			/>

			<div className="relative z-10 w-full max-w-[360px] mx-4">
				{/* Logo */}
				<div className="flex flex-col items-center mb-8 gap-3">
					<IoMark height={52} />
					<div className="text-center">
						<p className="text-[11px] font-mono text-zinc-600 tracking-widest uppercase mt-1">
							personal ai orchestrator
						</p>
					</div>
				</div>

				<form
					onSubmit={handleSubmit}
					className="glass-card border border-white/[0.07] rounded-2xl p-6 space-y-4"
				>
					<div className="space-y-1">
						<label className="text-[11px] font-mono text-zinc-500 block">Email</label>
						<input
							type="email"
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							required
							className="w-full bg-[#161616] border border-white/[0.08] rounded-xl px-3 py-2.5 text-sm text-zinc-200 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#E43A9C]/40 focus:ring-1 focus:ring-[#E43A9C]/15 transition-colors"
						/>
					</div>
					<div className="space-y-1">
						<label className="text-[11px] font-mono text-zinc-500 block">Password</label>
						<input
							type="password"
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							required
							placeholder="••••••••"
							className="w-full bg-[#161616] border border-white/[0.08] rounded-xl px-3 py-2.5 text-sm text-zinc-200 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#E43A9C]/40 focus:ring-1 focus:ring-[#E43A9C]/15 transition-colors"
						/>
					</div>

					{error && (
						<p className="text-[11px] font-mono text-red-400">{error}</p>
					)}

					<button
						type="submit"
						disabled={loading}
						className="w-full text-white font-mono text-sm rounded-xl py-3 mt-1 transition-opacity hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
						style={{
							background: 'linear-gradient(135deg, #D83333 0%, #E43A9C 55%, #F041FF 100%)',
						}}
					>
						{loading ? (
							<>
								<span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
								Authenticating…
							</>
						) : (
							'Sign In'
						)}
					</button>
				</form>
				<p className="text-center text-[11px] text-zinc-700 font-mono mt-4">
					Secured by Supabase Auth
				</p>
			</div>
		</div>
	);
}

// web/src/views/LoginView.vue
<template>
  <div class="flex items-center justify-center h-screen bg-gray-950">
    <div class="w-full max-w-sm p-8 bg-gray-900 rounded-xl border border-gray-800">
      <h1 class="text-2xl font-bold text-white text-center mb-2">IO</h1>
      <p class="text-gray-400 text-sm text-center mb-8">Sign in to continue</p>

      <form @submit.prevent="handleSignIn" class="space-y-4">
        <div>
          <label for="email" class="block text-sm font-medium text-gray-300 mb-1">Email</label>
          <input
            id="email"
            v-model="email"
            type="email"
            required
            autocomplete="email"
            class="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent"
            placeholder="you@example.com"
          />
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-300 mb-1">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            autocomplete="current-password"
            class="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent"
            placeholder="••••••••"
          />
        </div>

        <div v-if="error" class="text-red-400 text-sm">
          {{ error }}
        </div>

        <button
          type="submit"
          :disabled="auth.loading"
          class="w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
        >
          {{ auth.loading ? 'Signing in...' : 'Sign in' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const router = useRouter()

const email = ref('')
const password = ref('')
const error = ref<string | null>(null)

async function handleSignIn() {
  error.value = null
  const err = await auth.signIn(email.value, password.value)
  if (err) {
    error.value = err
  } else {
    router.push('/chat')
  }
}
</script>
