// packages/web/src/views/SchedulesView.tsx
import { Chip, PrimaryBtn, SecondaryBtn } from '@/components/ui/shared';
import { api } from '@/lib/api';
import { Calendar, Clock, Pause, Play, Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';

interface Schedule {
	id: string;
	name: string;
	targetType: 'squad' | 'orchestrator';
	targetId: string | null;
	cron: string;
	prompt: string;
	enabled: boolean;
	lastRun: string | null;
	nextRun: string | null;
}

export function SchedulesView() {
	const [schedules, setSchedules] = useState<Schedule[]>([]);
	const [tab, setTab] = useState<'all' | 'squad' | 'orchestrator'>('all');
	const [showCreate, setShowCreate] = useState(false);
	const [form, setForm] = useState({
		name: '',
		cron: '',
		prompt: '',
		targetType: 'orchestrator' as const,
	});

	useEffect(() => {
		loadSchedules();
	}, []);

	function loadSchedules() {
		api
			.get<{ schedules: Schedule[] }>('/schedules')
			.then((d) => setSchedules(d.schedules))
			.catch(() => {});
	}

	const filtered = schedules.filter((s) => tab === 'all' || s.targetType === tab);

	async function handleCreate() {
		if (!form.name || !form.cron || !form.prompt) return;
		try {
			await api.post('/schedules', form);
			toast.success(`Schedule "${form.name}" created`);
			setShowCreate(false);
			setForm({ name: '', cron: '', prompt: '', targetType: 'orchestrator' });
			loadSchedules();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to create');
		}
	}

	async function handleToggle(id: string, enabled: boolean) {
		try {
			await api.patch(`/schedules/${id}`, { enabled: !enabled });
			loadSchedules();
		} catch {
			toast.error('Failed to toggle schedule');
		}
	}

	async function handleDelete(id: string) {
		try {
			await api.delete(`/schedules/${id}`);
			toast.success('Schedule deleted');
			loadSchedules();
		} catch {
			toast.error('Failed to delete');
		}
	}

	return (
		<div className="flex-1 overflow-y-auto p-6">
			<div className="flex items-center justify-between mb-6">
				<div>
					<h2
						className="text-2xl tracking-wide text-zinc-100"
						style={{ fontFamily: "'Bebas Neue', sans-serif" }}
					>
						Schedules
					</h2>
					<p className="text-[11px] text-zinc-600 font-mono mt-0.5">
						{schedules.length} automated tasks · {schedules.filter((s) => s.enabled).length}{' '}
						active
					</p>
				</div>
				<PrimaryBtn onClick={() => setShowCreate(true)} className="px-3 py-1.5">
					<Plus className="w-3.5 h-3.5" /> New Schedule
				</PrimaryBtn>
			</div>

			{/* Tabs */}
			<div className="flex gap-1 mb-5 p-1 rounded-xl bg-white/[0.03] border border-white/[0.07] w-fit">
				{(['all', 'orchestrator', 'squad'] as const).map((t) => (
					<button
						key={t}
						type="button"
						onClick={() => setTab(t)}
						className={`px-3 py-1.5 rounded-lg text-[11px] font-mono transition-colors ${
							tab === t
								? 'bg-white/10 text-zinc-200'
								: 'text-zinc-600 hover:text-zinc-400'
						}`}
					>
						{t === 'all' ? 'All' : t === 'orchestrator' ? 'IO' : 'Squad'}
					</button>
				))}
			</div>

			{/* Create form */}
			{showCreate && (
				<div className="glass-card border border-white/[0.07] rounded-2xl p-5 mb-5">
					<h3
						className="text-base tracking-wide text-zinc-200 mb-3"
						style={{ fontFamily: "'Bebas Neue', sans-serif" }}
					>
						New Schedule
					</h3>
					<div className="space-y-3">
						<input
							type="text"
							placeholder="Name"
							value={form.name}
							onChange={(e) => setForm({ ...form, name: e.target.value })}
							className="w-full px-3 py-2 rounded-xl bg-white/[0.04] border border-white/[0.07] text-sm font-mono text-zinc-300 outline-none focus:border-[#E43A9C]/50"
						/>
						<input
							type="text"
							placeholder="Cron expression (e.g. 0 9 * * 1-5)"
							value={form.cron}
							onChange={(e) => setForm({ ...form, cron: e.target.value })}
							className="w-full px-3 py-2 rounded-xl bg-white/[0.04] border border-white/[0.07] text-sm font-mono text-zinc-300 outline-none focus:border-[#E43A9C]/50"
						/>
						<textarea
							placeholder="Prompt to execute"
							value={form.prompt}
							onChange={(e) => setForm({ ...form, prompt: e.target.value })}
							rows={3}
							className="w-full px-3 py-2 rounded-xl bg-white/[0.04] border border-white/[0.07] text-sm font-mono text-zinc-300 outline-none focus:border-[#E43A9C]/50 resize-none"
						/>
						<div className="flex gap-2">
							<PrimaryBtn onClick={handleCreate} className="px-3 py-1.5">
								Create
							</PrimaryBtn>
							<SecondaryBtn onClick={() => setShowCreate(false)} className="px-3 py-1.5">
								Cancel
							</SecondaryBtn>
						</div>
					</div>
				</div>
			)}

			{/* List */}
			<div className="space-y-2">
				{filtered.map((sched) => (
					<div
						key={sched.id}
						className="glass-card border border-white/[0.07] rounded-2xl p-4 flex items-center gap-4 group"
					>
						<div
							className={`w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 ${
								sched.enabled ? 'bg-[#E43A9C]/10' : 'bg-white/[0.04]'
							}`}
						>
							<Calendar
								size={14}
								className={sched.enabled ? 'text-[#E43A9C]' : 'text-zinc-600'}
							/>
						</div>
						<div className="flex-1 min-w-0">
							<div className="flex items-center gap-2">
								<span className="text-sm font-mono text-zinc-200">{sched.name}</span>
								<Chip variant={sched.targetType === 'orchestrator' ? 'info' : 'default'}>
									{sched.targetType === 'orchestrator' ? 'IO' : 'Squad'}
								</Chip>
								{!sched.enabled && <Chip variant="warning">Paused</Chip>}
							</div>
							<p className="text-[11px] text-zinc-600 font-mono mt-0.5">{sched.cron}</p>
							<p className="text-[11px] text-zinc-700 mt-0.5 truncate max-w-md">
								{sched.prompt}
							</p>
							{sched.nextRun && (
								<p className="text-[10px] text-zinc-700 font-mono mt-1 flex items-center gap-1">
									<Clock size={10} /> Next: {new Date(sched.nextRun).toLocaleString()}
								</p>
							)}
						</div>
						<div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
							<button
								type="button"
								onClick={() => handleToggle(sched.id, sched.enabled)}
								className={`p-1.5 rounded-lg transition-colors ${
									sched.enabled
										? 'text-emerald-400 hover:bg-emerald-400/10'
										: 'text-zinc-600 hover:bg-white/[0.04]'
								}`}
								title={sched.enabled ? 'Pause' : 'Resume'}
							>
								{sched.enabled ? <Pause size={13} /> : <Play size={13} />}
							</button>
							<button
								type="button"
								onClick={() => handleDelete(sched.id)}
								className="p-1.5 rounded-lg text-zinc-600 hover:text-red-400 hover:bg-red-400/10 transition-colors"
							>
								<Trash2 size={13} />
							</button>
						</div>
					</div>
				))}
			</div>

			{filtered.length === 0 && (
				<div className="text-center py-12">
					<Calendar size={48} className="mx-auto mb-3 text-zinc-800" />
					<p className="text-[11px] font-mono text-zinc-700">
						No schedules. Click New Schedule to create one.
					</p>
				</div>
			)}
		</div>
	);
}

// web/src/views/SchedulesView.vue
<template>
  <div class="flex flex-col h-full bg-gray-950">
    <div class="flex-1 overflow-y-auto p-6">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-2xl font-bold">Schedules</h2>
        <button
          @click="fetchSchedules"
          :disabled="loading"
          class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-white px-4 py-2 rounded-lg text-sm transition-colors"
        >
          ↻ Refresh
        </button>
      </div>

      <div v-if="loading" class="text-gray-400 text-center py-12">
        Loading schedules...
      </div>

      <div v-else-if="error" class="bg-red-900 text-red-100 p-4 rounded-lg mb-4">
        {{ error }}
      </div>

      <template v-else>
        <!-- IO Schedules -->
        <details open class="mb-6">
          <summary class="cursor-pointer select-none flex items-center gap-2 text-lg font-semibold text-gray-100 mb-4 py-2 border-b border-gray-700">
            <span class="text-gray-400 text-sm">▶</span>
            🤖 IO Schedules
            <span class="ml-2 text-xs font-normal text-gray-500 bg-gray-800 px-2 py-0.5 rounded-full">{{ ioSchedules.length }}</span>
          </summary>

          <div v-if="ioSchedules.length === 0" class="text-gray-500 italic text-sm py-4 text-center">
            No IO schedules configured.
          </div>

          <div v-else class="grid gap-3">
            <div
              v-for="s in ioSchedules"
              :key="s.id"
              class="bg-gray-800 border border-gray-700 rounded-lg p-4 hover:border-gray-600 transition-colors"
            >
              <div class="flex flex-wrap items-start justify-between gap-3">
                <!-- Info -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2 mb-1">
                    <span class="font-bold text-gray-100">{{ s.name }}</span>
                    <span :class="[
                      'px-2 py-0.5 rounded text-xs font-medium',
                      s.enabled ? 'bg-green-900 text-green-200' : 'bg-gray-700 text-gray-400'
                    ]">
                      {{ s.enabled ? 'Active' : 'Paused' }}
                    </span>
                  </div>
                  <div class="flex flex-wrap gap-4 text-sm text-gray-400 mt-1">
                    <span class="font-mono text-xs bg-gray-900 px-2 py-0.5 rounded">{{ s.cron_expr }}</span>
                    <span title="Next run">⏭ {{ s.next_run_at ? formatDate(s.next_run_at) : '—' }}</span>
                    <span title="Last run">🕐 {{ s.last_run_at ? formatDate(s.last_run_at) : '—' }}</span>
                  </div>
                  <p v-if="s.notes" class="text-xs text-gray-500 mt-1 truncate">{{ s.notes }}</p>
                </div>

                <!-- Actions -->
                <div class="flex items-center gap-2 shrink-0">
                  <button
                    v-if="s.enabled"
                    @click="pauseSchedule('io', s.id)"
                    :disabled="mutating.has(`io-${s.id}`)"
                    class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Pause"
                  >⏸ Pause</button>
                  <button
                    v-else
                    @click="resumeSchedule('io', s.id)"
                    :disabled="mutating.has(`io-${s.id}`)"
                    class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Resume"
                  >▶ Resume</button>
                  <button
                    @click="runNow('io', s.id)"
                    :disabled="mutating.has(`io-${s.id}`)"
                    class="bg-blue-700 hover:bg-blue-600 disabled:opacity-50 text-white text-xs px-3 py-1.5 rounded transition-colors"
                    title="Run now"
                  >▶ Run now</button>
                  <RouterLink
                    :to="`/activity?schedule=${encodeURIComponent(s.name)}`"
                    class="bg-gray-700 hover:bg-gray-600 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="View history"
                  >📋 History</RouterLink>
                  <button
                    @click="deleteSchedule('io', s.id, s.name)"
                    :disabled="mutating.has(`io-${s.id}`)"
                    class="bg-red-900 hover:bg-red-800 disabled:opacity-50 text-red-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Delete"
                  >🗑</button>
                </div>
              </div>
            </div>
          </div>
        </details>

        <!-- Squad Schedules -->
        <details open>
          <summary class="cursor-pointer select-none flex items-center gap-2 text-lg font-semibold text-gray-100 mb-4 py-2 border-b border-gray-700">
            <span class="text-gray-400 text-sm">▶</span>
            👥 Squad Schedules
            <span class="ml-2 text-xs font-normal text-gray-500 bg-gray-800 px-2 py-0.5 rounded-full">{{ squadSchedules.length }}</span>
          </summary>

          <div v-if="squadSchedules.length === 0" class="text-gray-500 italic text-sm py-4 text-center">
            No squad schedules configured.
          </div>

          <div v-else class="grid gap-3">
            <div
              v-for="s in squadSchedules"
              :key="s.id"
              class="bg-gray-800 border border-gray-700 rounded-lg p-4 hover:border-gray-600 transition-colors"
            >
              <div class="flex flex-wrap items-start justify-between gap-3">
                <!-- Info -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2 mb-1">
                    <span class="font-bold text-gray-100">{{ s.name }}</span>
                    <span class="text-xs text-gray-500 bg-gray-900 px-2 py-0.5 rounded">{{ s.squad_slug }}</span>
                    <span :class="[
                      'px-2 py-0.5 rounded text-xs font-medium',
                      s.enabled ? 'bg-green-900 text-green-200' : 'bg-gray-700 text-gray-400'
                    ]">
                      {{ s.enabled ? 'Active' : 'Paused' }}
                    </span>
                  </div>
                  <div class="flex flex-wrap gap-4 text-sm text-gray-400 mt-1">
                    <span class="font-mono text-xs bg-gray-900 px-2 py-0.5 rounded">{{ s.cron_expr }}</span>
                    <span title="Next run">⏭ {{ s.next_run_at ? formatDate(s.next_run_at) : '—' }}</span>
                    <span title="Last run">🕐 {{ s.last_run_at ? formatDate(s.last_run_at) : '—' }}</span>
                  </div>
                  <p v-if="s.notes" class="text-xs text-gray-500 mt-1 truncate">{{ s.notes }}</p>
                </div>

                <!-- Actions -->
                <div class="flex items-center gap-2 shrink-0">
                  <button
                    v-if="s.enabled"
                    @click="pauseSchedule('squads', s.id)"
                    :disabled="mutating.has(`squads-${s.id}`)"
                    class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Pause"
                  >⏸ Pause</button>
                  <button
                    v-else
                    @click="resumeSchedule('squads', s.id)"
                    :disabled="mutating.has(`squads-${s.id}`)"
                    class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Resume"
                  >▶ Resume</button>
                  <button
                    @click="runNow('squads', s.id)"
                    :disabled="mutating.has(`squads-${s.id}`)"
                    class="bg-blue-700 hover:bg-blue-600 disabled:opacity-50 text-white text-xs px-3 py-1.5 rounded transition-colors"
                    title="Run now"
                  >▶ Run now</button>
                  <RouterLink
                    :to="`/activity?schedule=${encodeURIComponent(s.name)}`"
                    class="bg-gray-700 hover:bg-gray-600 text-gray-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="View history"
                  >📋 History</RouterLink>
                  <button
                    @click="deleteSchedule('squads', s.id, s.name)"
                    :disabled="mutating.has(`squads-${s.id}`)"
                    class="bg-red-900 hover:bg-red-800 disabled:opacity-50 text-red-200 text-xs px-3 py-1.5 rounded transition-colors"
                    title="Delete"
                  >🗑</button>
                </div>
              </div>
            </div>
          </div>
        </details>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import { apiFetch } from '../lib/api'

interface IoSchedule {
  id: number
  name: string
  cron_expr: string
  prompt: string
  notes: string | null
  enabled: number
  created_at: string
  last_run_at: string | null
  next_run_at: string | null
}

interface SquadSchedule {
  id: number
  squad_slug: string
  name: string
  cron_expr: string
  prompt: string
  notes: string | null
  enabled: number
  created_at: string
  last_run_at: string | null
  next_run_at: string | null
}

const ioSchedules = ref<IoSchedule[]>([])
const squadSchedules = ref<SquadSchedule[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
const mutating = ref(new Set<string>())

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString()
}

async function fetchSchedules(): Promise<void> {
  loading.value = true
  error.value = null
  try {
    const res = await apiFetch('/api/schedules')
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = (await res.json()) as { io: IoSchedule[]; squads: SquadSchedule[] }
    ioSchedules.value = data.io
    squadSchedules.value = data.squads
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to load schedules'
  } finally {
    loading.value = false
  }
}

async function mutate(key: string, fn: () => Promise<void>): Promise<void> {
  if (mutating.value.has(key)) return
  mutating.value = new Set(mutating.value).add(key)
  try {
    await fn()
    await fetchSchedules()
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Action failed'
  } finally {
    const next = new Set(mutating.value)
    next.delete(key)
    mutating.value = next
  }
}

async function pauseSchedule(ns: 'io' | 'squads', id: number): Promise<void> {
  await mutate(`${ns}-${id}`, async () => {
    const res = await apiFetch(`/api/schedules/${ns}/${id}/pause`, { method: 'POST' })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
  })
}

async function resumeSchedule(ns: 'io' | 'squads', id: number): Promise<void> {
  await mutate(`${ns}-${id}`, async () => {
    const res = await apiFetch(`/api/schedules/${ns}/${id}/resume`, { method: 'POST' })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
  })
}

async function runNow(ns: 'io' | 'squads', id: number): Promise<void> {
  await mutate(`${ns}-${id}`, async () => {
    const res = await apiFetch(`/api/schedules/${ns}/${id}/run-now`, { method: 'POST' })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
  })
}

async function deleteSchedule(ns: 'io' | 'squads', id: number, name: string): Promise<void> {
  if (!window.confirm(`Delete schedule '${name}'?`)) return
  await mutate(`${ns}-${id}`, async () => {
    const res = await apiFetch(`/api/schedules/${ns}/${id}`, { method: 'DELETE' })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
  })
}

onMounted(fetchSchedules)
</script>
