// web/src/views/SettingsView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { apiGet, apiPut } from "@/lib/api";

const loading = ref(true);
const saving = ref(false);
const saved = ref(false);
const activeTab = ref("general");

const tabs = [
  { id: "general", label: "General" },
  { id: "telegram", label: "Telegram" },
  { id: "auth", label: "Auth" },
  { id: "advanced", label: "Advanced" },
];

const settings = ref({
  defaultModel: "",
  port: 3170,
  telegramEnabled: false,
  telegramBotToken: "",
  authorizedUserId: null as number | null,
  supabaseUrl: "",
  supabaseAnonKey: "",
  authorizedEmail: "",
  backgroundNotifyMode: "meaningful",
  backgroundNotifyTelegram: true,
  selfEditEnabled: false,
  watchdogEnabled: true,
});

async function fetchSettings() {
  loading.value = true;
  try {
    const data = await apiGet("/settings");
    settings.value = data;
  } finally {
    loading.value = false;
  }
}

async function saveSettings() {
  saving.value = true;
  saved.value = false;
  try {
    await apiPut("/settings", settings.value);
    saved.value = true;
    setTimeout(() => (saved.value = false), 2000);
  } finally {
    saving.value = false;
  }
}

onMounted(fetchSettings);
</script>

<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">Settings</h1>
      <button
        @click="saveSettings"
        :disabled="saving"
        class="px-4 py-2 rounded-md bg-primary text-primary-foreground text-sm hover:bg-primary/90 disabled:opacity-50"
      >
        {{ saving ? "Saving..." : saved ? "Saved ✓" : "Save" }}
      </button>
    </div>

    <div v-if="loading" class="text-muted-foreground">Loading...</div>

    <template v-else>
      <!-- Tabs -->
      <div class="flex gap-1 border-b border-border mb-6">
        <button
          v-for="tab in tabs"
          :key="tab.id"
          @click="activeTab = tab.id"
          class="px-4 py-2 text-sm font-medium border-b-2 transition-colors"
          :class="activeTab === tab.id ? 'border-primary text-foreground' : 'border-transparent text-muted-foreground hover:text-foreground'"
        >
          {{ tab.label }}
        </button>
      </div>

      <!-- General -->
      <div v-if="activeTab === 'general'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Default Model</label>
          <input v-model="settings.defaultModel" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
        <div>
          <label class="text-sm font-medium">Port</label>
          <input v-model.number="settings.port" type="number" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
          <p class="text-xs text-muted-foreground mt-1">Requires restart to take effect</p>
        </div>
        <div>
          <label class="text-sm font-medium">Background Notify Mode</label>
          <select v-model="settings.backgroundNotifyMode" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
            <option value="all">All</option>
            <option value="meaningful">Meaningful</option>
            <option value="off">Off</option>
          </select>
        </div>
        <div class="flex items-center gap-3">
          <input v-model="settings.backgroundNotifyTelegram" type="checkbox" id="notifyTelegram" class="rounded" />
          <label for="notifyTelegram" class="text-sm font-medium">Send notifications via Telegram</label>
        </div>
      </div>

      <!-- Telegram -->
      <div v-if="activeTab === 'telegram'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Bot Token</label>
          <input v-model="settings.telegramBotToken" type="password" placeholder="Enter new token to update" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
        <div>
          <label class="text-sm font-medium">Authorized User ID</label>
          <input v-model.number="settings.authorizedUserId" type="number" placeholder="123456789" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
        <div class="flex items-center gap-3">
          <input v-model="settings.telegramEnabled" type="checkbox" id="telegramEnabled" class="rounded" />
          <label for="telegramEnabled" class="text-sm font-medium">Enable Telegram Bot</label>
        </div>
      </div>

      <!-- Auth -->
      <div v-if="activeTab === 'auth'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Supabase URL</label>
          <input v-model="settings.supabaseUrl" placeholder="https://your-project.supabase.co" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
        <div>
          <label class="text-sm font-medium">Supabase Anon Key</label>
          <input v-model="settings.supabaseAnonKey" type="password" placeholder="Enter new key to update" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
        <div>
          <label class="text-sm font-medium">Authorized Email</label>
          <input v-model="settings.authorizedEmail" type="email" placeholder="you@example.com" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
      </div>

      <!-- Advanced -->
      <div v-if="activeTab === 'advanced'" class="space-y-4 max-w-lg">
        <div class="flex items-center gap-3">
          <input v-model="settings.selfEditEnabled" type="checkbox" id="selfEdit" class="rounded" />
          <div>
            <label for="selfEdit" class="text-sm font-medium">Self-Edit Mode</label>
            <p class="text-xs text-muted-foreground">Allow IO to modify its own source code</p>
          </div>
        </div>
        <div class="flex items-center gap-3">
          <input v-model="settings.watchdogEnabled" type="checkbox" id="watchdog" class="rounded" />
          <div>
            <label for="watchdog" class="text-sm font-medium">Watchdog</label>
            <p class="text-xs text-muted-foreground">Monitor event loop and zombie instances</p>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

// web/src/views/SettingsView.tsx
import { Eye, EyeOff, Save, X } from "lucide-react";
import { type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { PrimaryBtn, SecondaryBtn, Toggle } from "@/components/ui";
import { notifyError, notifySuccess } from "@/lib/notify";
import { useAuthStore } from "@/stores/auth";

type SettingsTab = "General" | "Telegram" | "Auth" | "Advanced";

interface SettingsForm {
  defaultModel: string;
  port: string;
  notificationMode: string;
  telegramToken: string;
  telegramUserId: string;
  telegramEnabled: boolean;
  supabaseUrl: string;
  supabaseAnonKey: string;
  authorizedEmail: string;
  modelTiers: {
    high: string[];
    medium: string[];
    low: string[];
  };
  selfEdit: boolean;
  watchdog: boolean;
}

const tabs: SettingsTab[] = ["General", "Telegram", "Auth", "Advanced"];
const MASK = "••••••••";
const inputClass =
  "bg-[#181818] border border-white/[0.06] rounded-xl px-3 py-2 text-[11px] text-zinc-300 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#66FCF1]/30";
const tabClass = "px-4 py-2 text-[11px] font-mono capitalize border-b-2 -mb-px";

const emptySettings: SettingsForm = {
  defaultModel: "",
  port: "3170",
  notificationMode: "meaningful",
  telegramToken: "",
  telegramUserId: "",
  telegramEnabled: false,
  supabaseUrl: "",
  supabaseAnonKey: "",
  authorizedEmail: "",
  modelTiers: {
    high: [],
    medium: [],
    low: [],
  },
  selfEdit: false,
  watchdog: true,
};

async function authJson<T>(paths: string[], init?: RequestInit): Promise<T> {
  const token = useAuthStore.getState().token;

  for (let index = 0; index < paths.length; index += 1) {
    const res = await fetch(paths[index], {
      ...init,
      headers: {
        "Content-Type": "application/json",
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(init?.headers ?? {}),
      },
    });

    if (res.ok) {
      if (res.status === 204) return undefined as T;
      return (await res.json()) as T;
    }

    if (res.status === 404 && index < paths.length - 1) continue;

    const message = await res.text();
    throw new Error(message || `Request failed: ${res.status}`);
  }

  throw new Error("Request failed");
}

function parseTier(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value
      .map(String)
      .map((item) => item.trim())
      .filter(Boolean);
  }
  if (typeof value === "string") {
    return value
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }
  return [];
}

function normalizeSettings(data: Record<string, unknown>): SettingsForm {
  return {
    defaultModel: String(data.defaultModel ?? data.model ?? ""),
    port: String(data.port ?? "3170"),
    notificationMode: String(data.notificationMode ?? data.backgroundNotifyMode ?? "meaningful"),
    telegramToken: String(data.telegramToken ?? data.telegramBotToken ?? ""),
    telegramUserId: String(data.telegramUserId ?? data.authorizedUserId ?? ""),
    telegramEnabled: Boolean(data.telegramEnabled),
    supabaseUrl: String(data.supabaseUrl ?? ""),
    supabaseAnonKey: String(data.supabaseAnonKey ?? ""),
    authorizedEmail: String(data.authorizedEmail ?? ""),
    modelTiers: {
      high: parseTier(
        data.modelTiers && typeof data.modelTiers === "object"
          ? (data.modelTiers as Record<string, unknown>).high
          : data.highModels,
      ),
      medium: parseTier(
        data.modelTiers && typeof data.modelTiers === "object"
          ? (data.modelTiers as Record<string, unknown>).medium
          : data.mediumModels,
      ),
      low: parseTier(
        data.modelTiers && typeof data.modelTiers === "object"
          ? (data.modelTiers as Record<string, unknown>).low
          : data.lowModels,
      ),
    },
    selfEdit: Boolean(data.selfEdit ?? data.selfEditEnabled),
    watchdog: Boolean(data.watchdog ?? data.watchdogEnabled ?? true),
  };
}

function buildPayload(settings: SettingsForm) {
  const telegramToken = settings.telegramToken === MASK ? undefined : settings.telegramToken;
  const supabaseAnonKey = settings.supabaseAnonKey === MASK ? undefined : settings.supabaseAnonKey;

  return {
    defaultModel: settings.defaultModel,
    port: Number(settings.port || 3170),
    notificationMode: settings.notificationMode,
    backgroundNotifyMode: settings.notificationMode,
    telegramToken,
    telegramBotToken: telegramToken,
    telegramUserId: settings.telegramUserId ? Number(settings.telegramUserId) : undefined,
    authorizedUserId: settings.telegramUserId ? Number(settings.telegramUserId) : undefined,
    telegramEnabled: settings.telegramEnabled,
    supabaseUrl: settings.supabaseUrl,
    supabaseAnonKey,
    authorizedEmail: settings.authorizedEmail,
    modelTiers: settings.modelTiers,
    selfEdit: settings.selfEdit,
    selfEditEnabled: settings.selfEdit,
    watchdog: settings.watchdog,
    watchdogEnabled: settings.watchdog,
  };
}

function FormRow({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-2 border-b border-white/[0.04] py-4 first:pt-0 last:border-b-0 last:pb-0 md:flex-row md:items-center">
      <div className="w-40 text-[11px] font-mono text-zinc-500">{label}</div>
      <div className="flex-1 flex justify-end">{children}</div>
    </div>
  );
}

function SensitiveField({
  value,
  placeholder,
  visible,
  onToggle,
  onChange,
}: {
  value: string;
  placeholder?: string;
  visible: boolean;
  onToggle: () => void;
  onChange: (value: string) => void;
}) {
  return (
    <div className="relative">
      <input
        type={visible ? "text" : "password"}
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        className={`${inputClass} w-full pr-10`}
      />
      <button
        type="button"
        onClick={onToggle}
        className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-600 transition-colors hover:text-zinc-300"
      >
        {visible ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
      </button>
    </div>
  );
}

export default function SettingsView() {
  const [settings, setSettings] = useState<SettingsForm>(emptySettings);
  const [initialSettings, setInitialSettings] = useState<SettingsForm>(emptySettings);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<SettingsTab>("General");
  const [showTelegramToken, setShowTelegramToken] = useState(false);
  const [showSupabaseKey, setShowSupabaseKey] = useState(false);

  const loadSettings = useCallback(async () => {
    const response = await authJson<Record<string, unknown>>(["/api/config", "/api/settings"]);
    const normalized = normalizeSettings(response);
    setSettings(normalized);
    setInitialSettings(normalized);
  }, []);

  useEffect(() => {
    void (async () => {
      try {
        await loadSettings();
      } catch (error) {
        notifyError(error instanceof Error ? error.message : "Failed to load settings");
      } finally {
        setLoading(false);
      }
    })();
  }, [loadSettings]);

  const dirty = useMemo(
    () => JSON.stringify(settings) !== JSON.stringify(initialSettings),
    [initialSettings, settings],
  );

  const updateField = <K extends keyof SettingsForm>(key: K, value: SettingsForm[K]) => {
    setSettings((current) => ({ ...current, [key]: value }));
  };

  const save = async () => {
    setSaving(true);
    try {
      await authJson(["/api/config", "/api/settings"], {
        method: "PUT",
        body: JSON.stringify(buildPayload(settings)),
      });
      setInitialSettings(settings);
      notifySuccess("Settings saved");
    } catch (error) {
      notifyError(error instanceof Error ? error.message : "Failed to save settings");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="p-6 text-[11px] font-mono text-zinc-500">Loading settings…</div>;
  }

  return (
    <div className="mx-auto flex h-full w-full max-w-5xl flex-col gap-6 p-6 text-zinc-200">
      <div className="flex items-end justify-between gap-4">
        <div>
          <h1 className="text-4xl leading-none text-white" style={{ fontFamily: "'Bebas Neue', sans-serif" }}>
            Settings
          </h1>
          <p className="mt-2 text-[11px] font-mono text-zinc-600">
            Control auth, notifications, models, and runtime behavior.
          </p>
        </div>
      </div>

      <div className="glass-card border border-white/[0.07] rounded-2xl overflow-hidden flex-1 min-h-0 flex flex-col">
        <div className="border-b border-white/[0.06] px-5 pt-4">
          <div className="flex gap-1 overflow-x-auto border-b border-white/[0.06]">
            {tabs.map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => setActiveTab(tab)}
                className={`${tabClass} ${
                  activeTab === tab
                    ? "text-[#66FCF1] border-[#66FCF1]"
                    : "text-zinc-600 hover:text-zinc-300 border-transparent"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5">
          {activeTab === "General" ? (
            <div className="space-y-1">
              <FormRow label="Default model">
                <input
                  value={settings.defaultModel}
                  onChange={(event) => updateField("defaultModel", event.target.value)}
                  placeholder="gpt-5"
                  className={`${inputClass} w-56`}
                />
              </FormRow>
              <FormRow label="Port">
                <input
                  type="number"
                  value={settings.port}
                  onChange={(event) => updateField("port", event.target.value)}
                  className={`${inputClass} w-24`}
                />
              </FormRow>
              <FormRow label="Notification mode">
                <select
                  value={settings.notificationMode}
                  onChange={(event) => updateField("notificationMode", event.target.value)}
                  className={`${inputClass} w-40`}
                >
                  <option value="all">all</option>
                  <option value="meaningful">meaningful</option>
                  <option value="off">off</option>
                </select>
              </FormRow>
            </div>
          ) : null}

          {activeTab === "Telegram" ? (
            <div className="space-y-1">
              <FormRow label="Enable">
                <Toggle
                  checked={settings.telegramEnabled}
                  onChange={() => updateField("telegramEnabled", !settings.telegramEnabled)}
                />
              </FormRow>
              <FormRow label="Bot token">
                <div className="w-48">
                  <SensitiveField
                    value={settings.telegramToken}
                    visible={showTelegramToken}
                    onToggle={() => setShowTelegramToken((current) => !current)}
                    onChange={(value) => updateField("telegramToken", value)}
                    placeholder="Telegram bot token"
                  />
                </div>
              </FormRow>
              <FormRow label="Authorized user ID">
                <input
                  value={settings.telegramUserId}
                  onChange={(event) => updateField("telegramUserId", event.target.value)}
                  placeholder="123456789"
                  className={`${inputClass} w-40`}
                />
              </FormRow>
            </div>
          ) : null}

          {activeTab === "Auth" ? (
            <div className="space-y-1">
              <FormRow label="Supabase URL">
                <input
                  value={settings.supabaseUrl}
                  onChange={(event) => updateField("supabaseUrl", event.target.value)}
                  placeholder="https://project.supabase.co"
                  className={`${inputClass} w-72`}
                />
              </FormRow>
              <FormRow label="Anon key">
                <div className="w-72">
                  <SensitiveField
                    value={settings.supabaseAnonKey}
                    visible={showSupabaseKey}
                    onToggle={() => setShowSupabaseKey((current) => !current)}
                    onChange={(value) => updateField("supabaseAnonKey", value)}
                    placeholder="Supabase anon key"
                  />
                </div>
              </FormRow>
              <FormRow label="Authorized email">
                <input
                  type="email"
                  value={settings.authorizedEmail}
                  onChange={(event) => updateField("authorizedEmail", event.target.value)}
                  placeholder="you@example.com"
                  className={`${inputClass} w-64`}
                />
              </FormRow>
            </div>
          ) : null}

          {activeTab === "Advanced" ? (
            <div className="space-y-1">
              <FormRow label="Self-edit">
                <Toggle checked={settings.selfEdit} onChange={() => updateField("selfEdit", !settings.selfEdit)} />
              </FormRow>
              <FormRow label="Watchdog">
                <Toggle checked={settings.watchdog} onChange={() => updateField("watchdog", !settings.watchdog)} />
              </FormRow>
            </div>
          ) : null}
        </div>

        <div className="border-t border-white/[0.06] px-5 py-4 flex items-center justify-between gap-3">
          <p className="text-[11px] font-mono text-zinc-600">
            {dirty ? "Unsaved changes" : `Secrets remain masked as ${MASK}`}
          </p>
          <div className="flex items-center gap-2">
            <SecondaryBtn
              onClick={() => setSettings(initialSettings)}
              className={`px-4 py-2 ${dirty ? "" : "pointer-events-none opacity-50"}`}
            >
              <X className="h-3.5 w-3.5" />
              Cancel
            </SecondaryBtn>
            <PrimaryBtn onClick={save} className={`px-4 py-2 ${saving ? "pointer-events-none opacity-60" : ""}`}>
              <Save className="h-3.5 w-3.5" />
              {saving ? "Saving…" : "Save"}
            </PrimaryBtn>
          </div>
        </div>
      </div>
    </div>
  );
}
