// web/src/views/SkillsView.tsx
import { useState, useEffect } from "react";
import { apiGet, apiPost, apiDelete, apiPut } from "@/lib/api";
import { MarkdownContent } from "@/components/MarkdownContent";
import { parseSkillContent, type ParsedSkill } from "@/lib/skill-frontmatter";
import { Plus, Trash2, Search, ExternalLink, Edit, Eye, X } from "lucide-react";

interface Skill {
  slug: string;
  name: string;
  description?: string;
  source?: string;
}

interface DiscoverSkill {
  slug: string;
  name: string;
  description: string;
  source: string;
  url: string;
}

export default function SkillsView() {
  const [skills, setSkills] = useState<Skill[]>([]);
  const [tab, setTab] = useState<"installed" | "discover">("installed");
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [newUrl, setNewUrl] = useState("");
  const [installError, setInstallError] = useState("");
  const [selectedSkill, setSelectedSkill] = useState<string | null>(null);
  const [skillContent, setSkillContent] = useState("");
  const [editMode, setEditMode] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [discoverQuery, setDiscoverQuery] = useState("");
  const [discoverResults, setDiscoverResults] = useState<DiscoverSkill[]>([]);
  const [discoverSource, setDiscoverSource] = useState<"awesome-copilot" | "skillssh">("awesome-copilot");
  const [discoverLoading, setDiscoverLoading] = useState(false);
  const [previewUrl, setPreviewUrl] = useState("");
  const [previewContent, setPreviewContent] = useState<ParsedSkill | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);

  useEffect(() => {
    apiGet<Skill[]>("/skills").then((data) => { setSkills(data); setLoading(false); });
  }, []);

  const installSkill = async () => {
    setInstallError("");
    try {
      const skill = await apiPost<Skill>("/skills", { url: newUrl });
      setSkills((prev) => [...prev, skill]);
      setNewUrl("");
      setShowCreate(false);
    } catch (err: unknown) {
      setInstallError(err instanceof Error ? err.message : "Install failed");
    }
  };

  const removeSkill = async (slug: string) => {
    await apiDelete(`/skills/${slug}`);
    setSkills((prev) => prev.filter((s) => s.slug !== slug));
    if (selectedSkill === slug) setSelectedSkill(null);
  };

  const viewContent = async (slug: string) => {
    setSelectedSkill(slug);
    setEditMode(false);
    const data = await apiGet<{ content: string }>(`/skills/${slug}/content`);
    setSkillContent(data.content);
  };

  const saveContent = async () => {
    if (!selectedSkill) return;
    await apiPut(`/skills/${selectedSkill}/content`, { content: editContent });
    setSkillContent(editContent);
    setEditMode(false);
  };

  const discover = async () => {
    setDiscoverLoading(true);
    try {
      const params = new URLSearchParams({ source: discoverSource });
      if (discoverQuery) params.set("q", discoverQuery);
      const data = await apiGet<DiscoverSkill[]>(`/skills/discover?${params}`);
      setDiscoverResults(data);
    } finally {
      setDiscoverLoading(false);
    }
  };

  useEffect(() => { if (tab === "discover") discover(); }, [tab, discoverSource]);

  const preview = async (url: string) => {
    setPreviewLoading(true);
    setPreviewUrl(url);
    try {
      const data = await apiGet<{ content: string }>(`/skills/preview?url=${encodeURIComponent(url)}`);
      setPreviewContent(parseSkillContent(data.content));
    } finally {
      setPreviewLoading(false);
    }
  };

  const installFromDiscover = async (skill: DiscoverSkill) => {
    const installed = await apiPost<Skill>("/skills", { source: skill.source, slug: skill.slug });
    setSkills((prev) => [...prev, installed]);
  };

  if (loading) return <div className="p-6 text-muted-foreground">Loading...</div>;

  return (
    <div className="flex h-full">
      {/* Left panel */}
      <div className="w-80 border-r border-border flex flex-col">
        <div className="p-4 border-b border-border">
          <div className="flex gap-2 mb-3">
            {(["installed", "discover"] as const).map((t) => (
              <button key={t} onClick={() => setTab(t)} className={`px-3 py-1.5 text-sm rounded-md ${tab === t ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground hover:bg-accent"}`}>
                {t === "installed" ? "Installed" : "Discover"}
              </button>
            ))}
          </div>
          {tab === "installed" && (
            <button onClick={() => setShowCreate(!showCreate)} className="flex items-center gap-1 text-sm text-primary hover:underline">
              <Plus size={14} /> Install from URL
            </button>
          )}
          {tab === "discover" && (
            <div className="space-y-2">
              <div className="flex gap-2">
                <select value={discoverSource} onChange={(e) => setDiscoverSource(e.target.value as typeof discoverSource)} className="px-2 py-1 text-xs bg-input border border-border rounded text-foreground">
                  <option value="awesome-copilot">awesome-copilot</option>
                  <option value="skillssh">skills.sh</option>
                </select>
              </div>
              <div className="flex gap-1">
                <input value={discoverQuery} onChange={(e) => setDiscoverQuery(e.target.value)} placeholder="Search..." className="flex-1 px-2 py-1 text-sm bg-input border border-border rounded text-foreground placeholder:text-muted-foreground focus:outline-none" />
                <button onClick={discover} className="px-2 py-1 bg-primary text-primary-foreground rounded text-sm"><Search size={14} /></button>
              </div>
            </div>
          )}
        </div>

        {showCreate && tab === "installed" && (
          <div className="p-4 border-b border-border space-y-2">
            <input value={newUrl} onChange={(e) => setNewUrl(e.target.value)} placeholder="Git URL or raw file URL" className="w-full px-3 py-2 bg-input border border-border rounded-md text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring" />
            {installError && <p className="text-xs text-destructive">{installError}</p>}
            <div className="flex gap-2">
              <button onClick={installSkill} className="px-3 py-1.5 bg-primary text-primary-foreground rounded-md text-sm">Install</button>
              <button onClick={() => setShowCreate(false)} className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded-md text-sm">Cancel</button>
            </div>
          </div>
        )}

        <div className="flex-1 overflow-y-auto">
          {tab === "installed" && skills.map((skill) => (
            <div
              key={skill.slug}
              onClick={() => viewContent(skill.slug)}
              className={`flex items-center gap-2 px-4 py-3 cursor-pointer border-b border-border hover:bg-accent/50 ${selectedSkill === skill.slug ? "bg-accent" : ""}`}
            >
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate">{skill.name || skill.slug}</p>
                {skill.description && <p className="text-xs text-muted-foreground truncate">{skill.description}</p>}
              </div>
              <button onClick={(e) => { e.stopPropagation(); removeSkill(skill.slug); }} className="text-muted-foreground hover:text-destructive">
                <Trash2 size={14} />
              </button>
            </div>
          ))}
          {tab === "discover" && (
            discoverLoading ? <p className="p-4 text-sm text-muted-foreground">Searching...</p> : (
              discoverResults.map((skill) => (
                <div key={skill.slug} className="px-4 py-3 border-b border-border">
                  <p className="text-sm font-medium">{skill.name}</p>
                  <p className="text-xs text-muted-foreground mb-2">{skill.description}</p>
                  <div className="flex gap-2">
                    <button onClick={() => installFromDiscover(skill)} className="text-xs text-primary hover:underline">Install</button>
                    <button onClick={() => preview(skill.url)} className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1"><Eye size={12} /> Preview</button>
                  </div>
                </div>
              ))
            )
          )}
        </div>
      </div>

      {/* Right panel */}
      <div className="flex-1 overflow-y-auto p-6">
        {previewContent && (
          <div className="mb-6 p-4 border border-border rounded-lg relative">
            <button onClick={() => setPreviewContent(null)} className="absolute top-2 right-2 text-muted-foreground hover:text-foreground"><X size={16} /></button>
            <h3 className="font-medium mb-2">Preview: {previewUrl}</h3>
            {previewContent.frontmatter.name && <p className="text-sm text-muted-foreground mb-2">{previewContent.frontmatter.description}</p>}
            <MarkdownContent content={previewContent.body} />
          </div>
        )}
        {selectedSkill && (
          <div>
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-lg font-bold">{selectedSkill}</h2>
              <button onClick={() => { setEditMode(true); setEditContent(skillContent); }} className="text-muted-foreground hover:text-foreground"><Edit size={16} /></button>
            </div>
            {editMode ? (
              <div className="space-y-3">
                <textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={20} className="w-full px-3 py-2 bg-input border border-border rounded-md text-sm text-foreground font-mono focus:outline-none focus:ring-2 focus:ring-ring" />
                <div className="flex gap-2">
                  <button onClick={saveContent} className="px-3 py-1.5 bg-primary text-primary-foreground rounded-md text-sm">Save</button>
                  <button onClick={() => setEditMode(false)} className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded-md text-sm">Cancel</button>
                </div>
              </div>
            ) : (
              <MarkdownContent content={skillContent} />
            )}
          </div>
        )}
        {!selectedSkill && !previewContent && (
          <div className="flex items-center justify-center h-full text-muted-foreground">
            Select a skill to view its content
          </div>
        )}
      </div>
    </div>
  );
}

// web/src/views/SkillsView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { apiGet, apiPost, apiPut, apiDelete } from "@/lib/api";
import { Puzzle, Plus, Trash2, Eye, Pencil, Save, X } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";

interface Skill {
  name: string;
  slug: string;
  description: string;
  path: string;
}

const skills = ref<Skill[]>([]);
const loading = ref(true);
const showAddForm = ref(false);
const newSkillUrl = ref("");
const adding = ref(false);
const error = ref("");

// View/Edit state
const selectedSkill = ref<Skill | null>(null);
const skillContent = ref("");
const editMode = ref(false);
const editContent = ref("");
const loadingContent = ref(false);

async function fetchSkills() {
  loading.value = true;
  try {
    skills.value = await apiGet("/skills");
  } finally {
    loading.value = false;
  }
}

async function addSkill() {
  if (!newSkillUrl.value.trim()) return;
  adding.value = true;
  error.value = "";
  try {
    await apiPost("/skills", { url: newSkillUrl.value.trim() });
    newSkillUrl.value = "";
    showAddForm.value = false;
    await fetchSkills();
  } catch (err: any) {
    error.value = err.message || "Failed to install skill";
  } finally {
    adding.value = false;
  }
}

async function removeSkill(slug: string) {
  try {
    await apiDelete(`/skills/${slug}`);
    if (selectedSkill.value?.slug === slug) {
      selectedSkill.value = null;
      skillContent.value = "";
    }
    await fetchSkills();
  } catch (err: any) {
    error.value = err.message || "Failed to remove skill";
  }
}

async function viewSkill(skill: Skill) {
  selectedSkill.value = skill;
  editMode.value = false;
  loadingContent.value = true;
  try {
    const data = await apiGet(`/skills/${skill.slug}/content`);
    skillContent.value = data.content;
  } catch (err: any) {
    skillContent.value = `Error loading skill: ${err.message}`;
  } finally {
    loadingContent.value = false;
  }
}

function startEdit() {
  editContent.value = skillContent.value;
  editMode.value = true;
}

async function saveSkill() {
  if (!selectedSkill.value) return;
  try {
    await apiPut(`/skills/${selectedSkill.value.slug}/content`, { content: editContent.value });
    skillContent.value = editContent.value;
    editMode.value = false;
    await fetchSkills();
  } catch (err: any) {
    error.value = err.message || "Failed to save skill";
  }
}

onMounted(fetchSkills);
</script>

<template>
  <div class="flex h-full">
    <!-- Sidebar: skill list -->
    <div class="w-72 border-r border-border flex flex-col shrink-0">
      <div class="p-3 border-b border-border space-y-2">
        <button
          @click="showAddForm = !showAddForm"
          class="w-full flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
        >
          <Plus class="w-3.5 h-3.5" />
          Add Skill
        </button>
        <div v-if="showAddForm" class="space-y-1.5">
          <input
            v-model="newSkillUrl"
            type="text"
            placeholder="https://github.com/user/skill-repo.git"
            class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
            @keyup.enter="addSkill"
          />
          <div class="flex gap-1">
            <button
              @click="addSkill"
              :disabled="adding || !newSkillUrl.trim()"
              class="flex-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              {{ adding ? "Installing..." : "Install" }}
            </button>
            <button
              @click="showAddForm = false; newSkillUrl = ''"
              class="px-2 py-1 text-xs rounded border border-border hover:bg-accent"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>

      <div class="flex-1 overflow-y-auto p-2">
        <div v-if="loading" class="text-xs text-muted-foreground p-2">Loading...</div>
        <div v-else-if="skills.length === 0" class="text-center py-8 text-muted-foreground">
          <Puzzle class="w-8 h-8 mx-auto mb-2 opacity-50" />
          <p class="text-xs">No skills installed.</p>
        </div>
        <div
          v-for="skill in skills"
          :key="skill.slug"
          @click="viewSkill(skill)"
          class="flex items-center justify-between px-2 py-2 text-xs rounded cursor-pointer hover:bg-accent transition-colors group"
          :class="{ 'bg-accent font-medium': selectedSkill?.slug === skill.slug }"
        >
          <div class="min-w-0 flex-1">
            <div class="font-medium truncate">{{ skill.name }}</div>
            <div class="text-muted-foreground truncate">{{ skill.slug }}</div>
          </div>
          <button
            @click.stop="removeSkill(skill.slug)"
            class="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-destructive/10 text-destructive transition-opacity shrink-0"
            title="Remove"
          >
            <Trash2 class="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>

    <!-- Content: skill viewer/editor -->
    <div class="flex-1 flex flex-col">
      <div v-if="!selectedSkill" class="flex items-center justify-center h-full text-muted-foreground">
        <div class="text-center">
          <Puzzle class="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p>Select a skill to view</p>
        </div>
      </div>

      <template v-else>
        <div class="flex items-center justify-between px-4 py-2 border-b border-border">
          <div>
            <span class="text-sm font-medium">{{ selectedSkill.name }}</span>
            <span class="text-xs text-muted-foreground ml-2 font-mono">{{ selectedSkill.slug }}/SKILL.md</span>
          </div>
          <div class="flex gap-1">
            <template v-if="!editMode">
              <button @click="startEdit" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Edit">
                <Pencil class="w-4 h-4" />
              </button>
            </template>
            <template v-else>
              <button @click="saveSkill" class="p-1.5 rounded hover:bg-accent text-green-500" title="Save">
                <Save class="w-4 h-4" />
              </button>
              <button @click="editMode = false" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Cancel">
                <X class="w-4 h-4" />
              </button>
            </template>
          </div>
        </div>

        <div class="flex-1 overflow-y-auto p-4">
          <div v-if="loadingContent" class="text-muted-foreground text-sm">Loading...</div>
          <textarea
            v-else-if="editMode"
            v-model="editContent"
            class="w-full h-full min-h-[400px] font-mono text-sm bg-background border border-input rounded-md p-3 focus:outline-none focus:ring-1 focus:ring-ring resize-none"
          ></textarea>
          <MarkdownContent v-else :content="skillContent" />
        </div>
      </template>
    </div>

    <p v-if="error" class="absolute bottom-4 left-4 text-sm text-destructive bg-background border border-destructive/30 px-3 py-2 rounded-md">{{ error }}</p>
  </div>
</template>
