// web/src/views/WikiView.tsx
import { useState, useEffect } from "react";
import { apiGet, apiPut, apiDelete } from "@/lib/api";
import { MarkdownContent } from "@/components/MarkdownContent";
import { WikiTree } from "@/components/WikiTree";
import { Plus, Edit, Trash2, Save, X, Link2 } from "lucide-react";

interface WikiPage {
  path: string;
  title: string;
}

export default function WikiView() {
  const [pages, setPages] = useState<WikiPage[]>([]);
  const [templates, setTemplates] = useState<WikiPage[]>([]);
  const [mode, setMode] = useState<"pages" | "templates">("pages");
  const [selectedPage, setSelectedPage] = useState<string | null>(null);
  const [content, setContent] = useState("");
  const [editMode, setEditMode] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [backlinks, setBacklinks] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [showNewPage, setShowNewPage] = useState(false);
  const [newPagePath, setNewPagePath] = useState("");
  const [search, setSearch] = useState("");

  const fetchPages = async () => {
    const data = await apiGet<WikiPage[]>("/wiki/pages");
    setPages(data);
    const tmpl = await apiGet<WikiPage[]>("/wiki/templates/squad");
    setTemplates(tmpl);
    setLoading(false);
  };

  useEffect(() => { fetchPages(); }, []);

  const selectPage = async (path: string) => {
    setSelectedPage(path);
    setEditMode(false);
    const endpoint = mode === "pages" ? `/wiki/page/${encodeURIComponent(path)}` : `/wiki/template/squad/${encodeURIComponent(path)}`;
    const data = await apiGet<{ content: string }>(endpoint);
    setContent(data.content);
    if (mode === "pages") {
      const bl = await apiGet<string[]>(`/wiki/backlinks/${encodeURIComponent(path)}`);
      setBacklinks(bl);
    } else {
      setBacklinks([]);
    }
  };

  const savePage = async () => {
    if (!selectedPage) return;
    const endpoint = mode === "pages" ? `/wiki/page/${encodeURIComponent(selectedPage)}` : `/wiki/template/squad/${encodeURIComponent(selectedPage)}`;
    await apiPut(endpoint, { content: editContent });
    setContent(editContent);
    setEditMode(false);
  };

  const deletePage = async () => {
    if (!selectedPage) return;
    const endpoint = mode === "pages" ? `/wiki/page/${encodeURIComponent(selectedPage)}` : `/wiki/template/squad/${encodeURIComponent(selectedPage)}`;
    await apiDelete(endpoint);
    setSelectedPage(null);
    setContent("");
    await fetchPages();
  };

  const createPage = async () => {
    if (!newPagePath) return;
    const endpoint = mode === "pages" ? `/wiki/page/${encodeURIComponent(newPagePath)}` : `/wiki/template/squad/${encodeURIComponent(newPagePath)}`;
    await apiPut(endpoint, { content: `# ${newPagePath}\n\n` });
    setShowNewPage(false);
    setNewPagePath("");
    await fetchPages();
    selectPage(newPagePath);
  };

  const currentPages = mode === "pages" ? pages : templates;
  const filteredPages = search ? currentPages.filter((p) => p.path.toLowerCase().includes(search.toLowerCase()) || p.title.toLowerCase().includes(search.toLowerCase())) : currentPages;

  if (loading) return <div className="p-6 text-muted-foreground">Loading...</div>;

  return (
    <div className="flex h-full">
      {/* Left panel */}
      <div className="w-72 border-r border-border flex flex-col">
        <div className="p-3 border-b border-border space-y-2">
          <div className="flex gap-2">
            {(["pages", "templates"] as const).map((m) => (
              <button key={m} onClick={() => { setMode(m); setSelectedPage(null); }} className={`px-2 py-1 text-xs rounded ${mode === m ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground"}`}>
                {m === "pages" ? "Pages" : "Templates"}
              </button>
            ))}
          </div>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search..."
            className="w-full px-2 py-1 text-sm bg-input border border-border rounded text-foreground placeholder:text-muted-foreground focus:outline-none"
          />
          <button onClick={() => setShowNewPage(true)} className="flex items-center gap-1 text-xs text-primary hover:underline">
            <Plus size={12} /> New {mode === "pages" ? "page" : "template"}
          </button>
        </div>

        {showNewPage && (
          <div className="p-3 border-b border-border space-y-2">
            <input value={newPagePath} onChange={(e) => setNewPagePath(e.target.value)} placeholder="path/to/page" className="w-full px-2 py-1 text-sm bg-input border border-border rounded text-foreground placeholder:text-muted-foreground focus:outline-none" />
            <div className="flex gap-2">
              <button onClick={createPage} className="px-2 py-1 text-xs bg-primary text-primary-foreground rounded">Create</button>
              <button onClick={() => setShowNewPage(false)} className="px-2 py-1 text-xs bg-secondary text-secondary-foreground rounded">Cancel</button>
            </div>
          </div>
        )}

        <div className="flex-1 overflow-y-auto">
          <WikiTree
            pages={filteredPages}
            selectedPage={selectedPage}
            onSelect={selectPage}
          />
        </div>
      </div>

      {/* Right panel */}
      <div className="flex-1 overflow-y-auto p-6">
        {selectedPage ? (
          <div>
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-lg font-bold flex-1">{selectedPage}</h2>
              {!editMode && (
                <>
                  <button onClick={() => { setEditMode(true); setEditContent(content); }} className="text-muted-foreground hover:text-foreground"><Edit size={16} /></button>
                  <button onClick={deletePage} className="text-muted-foreground hover:text-destructive"><Trash2 size={16} /></button>
                </>
              )}
            </div>
            {editMode ? (
              <div className="space-y-3">
                <textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={20} className="w-full px-3 py-2 bg-input border border-border rounded-md text-sm text-foreground font-mono focus:outline-none focus:ring-2 focus:ring-ring" />
                <div className="flex gap-2">
                  <button onClick={savePage} className="flex items-center gap-1 px-3 py-1.5 bg-primary text-primary-foreground rounded-md text-sm"><Save size={14} /> Save</button>
                  <button onClick={() => setEditMode(false)} className="flex items-center gap-1 px-3 py-1.5 bg-secondary text-secondary-foreground rounded-md text-sm"><X size={14} /> Cancel</button>
                </div>
              </div>
            ) : (
              <>
                <MarkdownContent content={content} />
                {backlinks.length > 0 && (
                  <div className="mt-6 pt-4 border-t border-border">
                    <h3 className="text-sm font-medium text-muted-foreground mb-2 flex items-center gap-1"><Link2 size={14} /> Backlinks</h3>
                    <div className="flex flex-wrap gap-2">
                      {backlinks.map((bl) => (
                        <button key={bl} onClick={() => selectPage(bl)} className="text-xs px-2 py-1 bg-muted rounded hover:bg-accent">{bl}</button>
                      ))}
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        ) : (
          <div className="flex items-center justify-center h-full text-muted-foreground">
            Select a page to view
          </div>
        )}
      </div>
    </div>
  );
}

// web/src/views/WikiView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { apiGet, apiPut, apiDelete } from "@/lib/api";
import { BookOpen, Search, Plus, Pencil, Trash2, Save, X } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";

const pages = ref<string[]>([]);
const selectedPage = ref<string | null>(null);
const pageContent = ref("");
const editMode = ref(false);
const editContent = ref("");
const searchQuery = ref("");
const loading = ref(true);
const showNewForm = ref(false);
const newPagePath = ref("");

onMounted(async () => {
  try {
    pages.value = await apiGet("/wiki/pages");
  } finally {
    loading.value = false;
  }
});

async function selectPage(path: string) {
  selectedPage.value = path;
  editMode.value = false;
  const data = await apiGet(`/wiki/page/${path}`);
  pageContent.value = data.content;
}

function startEdit() {
  editContent.value = pageContent.value;
  editMode.value = true;
}

async function savePage() {
  if (!selectedPage.value) return;
  await apiPut(`/wiki/page/${selectedPage.value}`, { content: editContent.value });
  pageContent.value = editContent.value;
  editMode.value = false;
}

async function deletePage() {
  if (!selectedPage.value) return;
  if (!confirm(`Delete "${selectedPage.value}"?`)) return;
  await apiDelete(`/wiki/page/${selectedPage.value}`);
  pages.value = pages.value.filter((p) => p !== selectedPage.value);
  selectedPage.value = null;
  pageContent.value = "";
}

async function createPage() {
  const path = newPagePath.value.trim();
  if (!path) return;
  // Ensure .md extension
  const fullPath = path.endsWith(".md") ? path : `${path}.md`;
  await apiPut(`/wiki/page/${fullPath}`, { content: "" });
  if (!pages.value.includes(fullPath)) {
    pages.value.push(fullPath);
    pages.value.sort();
  }
  showNewForm.value = false;
  newPagePath.value = "";
  // Open the new page in edit mode
  selectedPage.value = fullPath;
  pageContent.value = "";
  editContent.value = "";
  editMode.value = true;
}

const filteredPages = () => {
  if (!searchQuery.value) return pages.value;
  const q = searchQuery.value.toLowerCase();
  return pages.value.filter((p) => p.toLowerCase().includes(q));
};
</script>

<template>
  <div class="flex h-full">
    <!-- Sidebar file tree -->
    <div class="w-64 border-r border-border flex flex-col shrink-0">
      <div class="p-3 border-b border-border space-y-2">
        <div class="relative">
          <Search class="absolute left-2.5 top-2.5 w-3.5 h-3.5 text-muted-foreground" />
          <input
            v-model="searchQuery"
            placeholder="Search pages..."
            class="w-full rounded-md border border-input bg-background pl-8 pr-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
          />
        </div>
        <button
          @click="showNewForm = !showNewForm"
          class="w-full flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
        >
          <Plus class="w-3.5 h-3.5" />
          New Page
        </button>
        <div v-if="showNewForm" class="space-y-1.5">
          <input
            v-model="newPagePath"
            placeholder="path/to/page.md"
            class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
            @keyup.enter="createPage"
          />
          <div class="flex gap-1">
            <button
              @click="createPage"
              :disabled="!newPagePath.trim()"
              class="flex-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              Create
            </button>
            <button
              @click="showNewForm = false; newPagePath = ''"
              class="px-2 py-1 text-xs rounded border border-border hover:bg-accent"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
      <div class="flex-1 overflow-y-auto p-2">
        <div v-if="loading" class="text-xs text-muted-foreground p-2">Loading...</div>
        <button
          v-for="page in filteredPages()"
          :key="page"
          @click="selectPage(page)"
          class="w-full text-left px-2 py-1.5 text-xs rounded hover:bg-accent truncate transition-colors"
          :class="{ 'bg-accent font-medium': selectedPage === page }"
        >
          📄 {{ page }}
        </button>
      </div>
    </div>

    <!-- Content -->
    <div class="flex-1 flex flex-col">
      <div v-if="!selectedPage" class="flex items-center justify-center h-full text-muted-foreground">
        <div class="text-center">
          <BookOpen class="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p>Select a page to view</p>
        </div>
      </div>

      <template v-else>
        <!-- Toolbar -->
        <div class="flex items-center justify-between px-4 py-2 border-b border-border">
          <span class="text-sm font-medium font-mono">{{ selectedPage }}</span>
          <div class="flex gap-1">
            <template v-if="!editMode">
              <button @click="startEdit" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Edit">
                <Pencil class="w-4 h-4" />
              </button>
              <button @click="deletePage" class="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive" title="Delete">
                <Trash2 class="w-4 h-4" />
              </button>
            </template>
            <template v-else>
              <button @click="savePage" class="p-1.5 rounded hover:bg-accent text-green-500" title="Save">
                <Save class="w-4 h-4" />
              </button>
              <button @click="editMode = false" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Cancel">
                <X class="w-4 h-4" />
              </button>
            </template>
          </div>
        </div>

        <!-- Content area -->
        <div class="flex-1 overflow-y-auto p-4">
          <textarea
            v-if="editMode"
            v-model="editContent"
            class="w-full h-full min-h-[400px] font-mono text-sm bg-background border border-input rounded-md p-3 focus:outline-none focus:ring-1 focus:ring-ring resize-none"
          ></textarea>
          <MarkdownContent v-else :content="pageContent" />
        </div>
      </template>
    </div>
  </div>
</template>
