// web/src/views/ChatView.vue
<script setup lang="ts">
import { ref, nextTick, onMounted } from "vue";
import { useChatStore } from "@/stores/chat";
import { Send, Square } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";

const chat = useChatStore();
const input = ref("");
const messagesContainer = ref<HTMLElement>();

async function send() {
  const text = input.value.trim();
  if (!text || chat.isStreaming) return;
  input.value = "";
  await chat.sendMessage(text);
  await nextTick();
  scrollToBottom();
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    send();
  }
}

onMounted(() => scrollToBottom());
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Messages -->
    <div ref="messagesContainer" class="flex-1 overflow-y-auto p-4 space-y-4">
      <div v-if="chat.messages.length === 0" class="flex items-center justify-center h-full">
        <div class="text-center text-muted-foreground">
          <div class="text-4xl mb-3">🤖</div>
          <p class="text-lg font-medium">Welcome to IO</p>
          <p class="text-sm mt-1">Send a message to get started.</p>
        </div>
      </div>

      <div
        v-for="msg in chat.messages"
        :key="msg.id"
        class="flex"
        :class="msg.role === 'user' ? 'justify-end' : 'justify-start'"
      >
        <div
          class="max-w-[75%] rounded-lg px-4 py-2 text-sm"
          :class="
            msg.role === 'user'
              ? 'bg-blue-600 text-white'
              : 'bg-muted text-foreground'
          "
        >
          <MarkdownContent v-if="msg.content" :content="msg.content" :class="msg.role === 'user' ? 'prose-invert' : ''" />
          <span v-else class="text-muted-foreground">...</span>
          <div
            v-if="msg.streaming"
            class="inline-block w-2 h-4 bg-current animate-pulse ml-1"
          ></div>
        </div>
      </div>
    </div>

    <!-- Input -->
    <div class="border-t border-border p-4">
      <div class="flex gap-2 items-end">
        <textarea
          v-model="input"
          @keydown="handleKeydown"
          placeholder="Send a message..."
          rows="1"
          class="flex-1 resize-none rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring min-h-[40px] max-h-[120px]"
        ></textarea>
        <button
          @click="send"
          :disabled="!input.trim() || chat.isStreaming"
          class="rounded-md bg-primary text-primary-foreground p-2 hover:bg-primary/90 disabled:opacity-50 transition-colors"
        >
          <Send v-if="!chat.isStreaming" class="w-4 h-4" />
          <Square v-else class="w-4 h-4" />
        </button>
      </div>
    </div>
  </div>
</template>

// packages/web/src/views/ChatView.tsx
import { IoMark } from '@/components/ui/io-mark';
import { Chip } from '@/components/ui/shared';
import { type WsMessage, useWebSocket } from '@/hooks/use-websocket';
import { api } from '@/lib/api';
import { Activity, ChevronDown, Paperclip, Send, Square } from 'lucide-react';
import { marked } from 'marked';
import { useCallback, useEffect, useRef, useState } from 'react';

interface ToolCall {
	name: string;
	status: 'running' | 'done' | 'error';
	result?: string;
}

interface Message {
	id: string;
	role: 'user' | 'assistant';
	content: string;
	timestamp: string;
	toolCall?: ToolCall;
}

export function ChatView() {
	const [messages, setMessages] = useState<Message[]>([]);
	const [input, setInput] = useState('');
	const [streaming, setStreaming] = useState('');
	const [isStreaming, setIsStreaming] = useState(false);
	const [expandedTool, setExpandedTool] = useState<string | null>(null);
	const messagesEndRef = useRef<HTMLDivElement>(null);
	const textareaRef = useRef<HTMLTextAreaElement>(null);

	// Load conversation history
	useEffect(() => {
		api
			.get<{ messages: Message[] }>('/conversations?limit=50')
			.then((data) => setMessages(data.messages))
			.catch(() => {});
	}, []);

	const handleDelta = useCallback((accumulated: string) => {
		setIsStreaming(true);
		setStreaming(accumulated);
	}, []);

	const handleMessage = useCallback((content: string) => {
		setIsStreaming(false);
		setStreaming('');
		setMessages((prev) => [
			...prev,
			{
				id: crypto.randomUUID(),
				role: 'assistant',
				content,
				timestamp: new Date().toLocaleTimeString('en-US', {
					hour: '2-digit',
					minute: '2-digit',
					hour12: false,
				}),
			},
		]);
	}, []);

	const handleEvent = useCallback((_msg: WsMessage) => {}, []);

	const { sendMessage } = useWebSocket({
		onDelta: handleDelta,
		onMessage: handleMessage,
		onEvent: handleEvent,
	});

	// Auto-scroll
	useEffect(() => {
		messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
	}, [messages, streaming]);

	function handleSend() {
		const text = input.trim();
		if (!text || isStreaming) return;

		const ts = new Date().toLocaleTimeString('en-US', {
			hour: '2-digit',
			minute: '2-digit',
			hour12: false,
		});
		setMessages((prev) => [...prev, { id: crypto.randomUUID(), role: 'user', content: text, timestamp: ts }]);
		setInput('');
		if (textareaRef.current) textareaRef.current.style.height = 'auto';
		sendMessage(text);
	}

	function handleKeyDown(e: React.KeyboardEvent) {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSend();
		}
	}

	function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
		setInput(e.target.value);
		if (textareaRef.current) {
			textareaRef.current.style.height = 'auto';
			textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 160)}px`;
		}
	}

	return (
		<div className="flex flex-col flex-1 min-h-0">
			{/* Messages */}
			<div className="flex-1 overflow-y-auto px-5 py-5 space-y-5">
				{messages.map((msg) => (
					<div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
						{/* Avatar */}
						<div
							className={`flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center text-[10px] font-mono mt-0.5 ${
								msg.role === 'user'
									? 'border border-[#E43A9C]/30 text-[#E43A9C]'
									: 'bg-[#282828] border border-white/[0.07] text-zinc-500'
							}`}
							style={msg.role === 'user' ? { background: 'rgba(228,58,156,0.12)' } : undefined}
						>
							{msg.role === 'user' ? 'U' : <IoMark height={12} />}
						</div>

						{/* Content */}
						<div
							className={`flex flex-col gap-1.5 max-w-[72%] ${msg.role === 'user' ? 'items-end' : 'items-start'}`}
						>
							{/* Tool call card */}
							{msg.toolCall && (
								<button
									type="button"
									onClick={() => setExpandedTool(expandedTool === msg.id ? null : msg.id)}
									className="w-full text-left border border-white/[0.07] bg-[#1e1e1e] rounded-xl px-3 py-2 flex items-center gap-2 hover:border-[#E43A9C]/25 transition-colors"
								>
									<Activity className="w-3 h-3 text-[#E43A9C] flex-shrink-0" />
									<span className="text-[11px] font-mono text-zinc-400 flex-1">
										{msg.toolCall.name}
									</span>
									<Chip
										variant={
											msg.toolCall.status === 'done'
												? 'success'
												: msg.toolCall.status === 'error'
													? 'error'
													: 'warning'
										}
									>
										{msg.toolCall.status}
									</Chip>
									<ChevronDown
										className={`w-3 h-3 text-zinc-600 transition-transform flex-shrink-0 ${expandedTool === msg.id ? 'rotate-180' : ''}`}
									/>
								</button>
							)}
							{msg.toolCall && expandedTool === msg.id && (
								<div className="w-full bg-[#181818] border border-white/[0.06] rounded-xl px-3 py-2">
									<p className="text-[11px] font-mono text-zinc-500">{msg.toolCall.result}</p>
								</div>
							)}

							{/* Message bubble */}
							<div
								className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
									msg.role === 'user'
										? 'text-white rounded-tr-sm'
										: 'bg-[#222222] border border-white/[0.07] text-zinc-200 rounded-tl-sm'
								}`}
								style={
									msg.role === 'user'
										? { background: 'linear-gradient(135deg, #D83333 0%, #C0285E 100%)' }
										: undefined
								}
							>
								{msg.role === 'user' ? (
									<p className="whitespace-pre-wrap">{msg.content}</p>
								) : (
									<div
										className="prose-io"
										// biome-ignore lint: markdown rendering
										dangerouslySetInnerHTML={{ __html: marked.parse(msg.content) as string }}
									/>
								)}
							</div>

							{/* Timestamp */}
							<span className="text-[11px] text-zinc-700 font-mono px-0.5">{msg.timestamp}</span>
						</div>
					</div>
				))}

				{/* Streaming indicator */}
				{isStreaming && streaming && (
					<div className="flex gap-3">
						<div className="flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center bg-[#282828] border border-white/[0.07] mt-0.5">
							<IoMark height={12} />
						</div>
						<div className="bg-[#222222] border border-white/[0.07] rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[72%]">
							<div
								className="prose-io text-sm"
								// biome-ignore lint: streaming markdown
								dangerouslySetInnerHTML={{ __html: marked.parse(streaming) as string }}
							/>
						</div>
					</div>
				)}

				{/* Streaming dots (no content yet) */}
				{isStreaming && !streaming && (
					<div className="flex gap-3">
						<div className="flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center bg-[#282828] border border-white/[0.07] mt-0.5">
							<IoMark height={12} />
						</div>
						<div className="bg-[#222222] border border-white/[0.07] rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1.5">
							{[0, 120, 240].map((d) => (
								<span
									key={d}
									className="w-1.5 h-1.5 rounded-full bg-[#E43A9C] animate-bounce"
									style={{ animationDelay: `${d}ms` }}
								/>
							))}
						</div>
					</div>
				)}

				<div ref={messagesEndRef} />
			</div>

			{/* Input area */}
			<div className="border-t border-white/[0.06] p-4 flex-shrink-0">
				<div className="bg-[#1e1e1e] border border-white/[0.08] rounded-2xl overflow-hidden transition-colors focus-within:border-[#E43A9C]/30">
					<textarea
						ref={textareaRef}
						value={input}
						onChange={handleInput}
						onKeyDown={handleKeyDown}
						placeholder="Message IO…"
						rows={1}
						className="w-full bg-transparent px-4 pt-3 pb-1 text-sm text-zinc-200 placeholder:text-zinc-700 resize-none focus:outline-none"
						style={{ minHeight: '42px', maxHeight: '160px', fontFamily: 'Inter, sans-serif' }}
					/>
					<div className="flex items-center justify-between px-3 pb-2.5">
						<button
							type="button"
							className="p-1.5 rounded-lg hover:bg-white/[0.05] text-zinc-700 hover:text-zinc-400 transition-colors"
						>
							<Paperclip className="w-4 h-4" />
						</button>
						<div className="flex items-center gap-2">
							{isStreaming ? (
								<button
									type="button"
									onClick={() => setIsStreaming(false)}
									className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-[11px] font-mono text-zinc-300 transition-colors"
								>
									<Square className="w-3 h-3" /> Stop
								</button>
							) : (
								<button
									type="button"
									onClick={handleSend}
									disabled={!input.trim()}
									className="p-2 rounded-xl text-white disabled:opacity-30 disabled:cursor-not-allowed transition-opacity hover:opacity-90"
									style={{ background: 'linear-gradient(135deg, #D83333, #E43A9C)' }}
								>
									<Send className="w-3.5 h-3.5" />
								</button>
							)}
						</div>
					</div>
				</div>
				<p className="text-center text-[11px] text-zinc-800 font-mono mt-2">
					IO may make mistakes. Verify important outputs.
				</p>
			</div>
		</div>
	);
}
