// web/src/views/FeedView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { apiGet, apiPost, apiDelete } from "@/lib/api";
import { Inbox, Check, Trash2 } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";

interface FeedItem {
  id: string;
  source: string;
  title: string;
  content: string;
  read: number;
  created_at: string;
}

const items = ref<FeedItem[]>([]);
const unreadCount = ref(0);
const filter = ref<"all" | "unread">("all");
const loading = ref(true);
const expandedId = ref<string | null>(null);

async function loadFeed() {
  loading.value = true;
  try {
    const data = await apiGet(`/feed?unread=${filter.value === "unread"}`);
    items.value = data.items;
    unreadCount.value = data.unreadCount;
  } finally {
    loading.value = false;
  }
}

async function markRead(id: string) {
  await apiPost(`/feed/${id}/read`);
  const item = items.value.find((i) => i.id === id);
  if (item) {
    item.read = 1;
    unreadCount.value = Math.max(0, unreadCount.value - 1);
  }
}

async function deleteItem(id: string) {
  await apiDelete(`/feed/${id}`);
  items.value = items.value.filter((i) => i.id !== id);
}

function toggle(id: string) {
  expandedId.value = expandedId.value === id ? null : id;
  if (expandedId.value === id) markRead(id);
}

onMounted(loadFeed);
</script>

<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">Feed</h1>
      <div class="flex gap-2">
        <button
          v-for="f in (['all', 'unread'] as const)"
          :key="f"
          @click="filter = f; loadFeed()"
          class="px-3 py-1.5 text-xs rounded-md border transition-colors"
          :class="filter === f ? 'bg-primary text-primary-foreground border-primary' : 'border-border text-muted-foreground hover:text-foreground'"
        >
          {{ f === 'all' ? 'All' : `Unread (${unreadCount})` }}
        </button>
      </div>
    </div>

    <div v-if="loading" class="text-muted-foreground">Loading...</div>

    <div v-else-if="items.length === 0" class="text-center py-12 text-muted-foreground">
      <Inbox class="w-12 h-12 mx-auto mb-3 opacity-50" />
      <p>No feed items.</p>
    </div>

    <div v-else class="space-y-2">
      <div
        v-for="item in items"
        :key="item.id"
        class="border border-border rounded-lg overflow-hidden"
        :class="{ 'border-l-2 border-l-primary': !item.read }"
      >
        <div
          @click="toggle(item.id)"
          class="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-muted/50 transition-colors"
        >
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <span class="text-xs bg-secondary text-secondary-foreground px-2 py-0.5 rounded-full">
                {{ item.source }}
              </span>
              <span class="text-sm font-medium truncate" :class="{ 'font-bold': !item.read }">
                {{ item.title }}
              </span>
            </div>
            <p class="text-xs text-muted-foreground mt-0.5">{{ item.created_at }}</p>
          </div>
          <div class="flex gap-1">
            <button
              v-if="!item.read"
              @click.stop="markRead(item.id)"
              class="p-1.5 rounded hover:bg-accent text-muted-foreground"
              title="Mark as read"
            >
              <Check class="w-3.5 h-3.5" />
            </button>
            <button
              @click.stop="deleteItem(item.id)"
              class="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive"
              title="Delete"
            >
              <Trash2 class="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
        <div v-if="expandedId === item.id" class="px-4 pb-3 border-t border-border pt-3">
          <MarkdownContent :content="item.content" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/web/src/views/FeedView.tsx
import { Chip } from '@/components/ui/shared';
import { api } from '@/lib/api';
import { Inbox, Mail, MailOpen } from 'lucide-react';
import { marked } from 'marked';
import { useEffect, useState } from 'react';

interface FeedItem {
	id: string;
	kind: string;
	title: string;
	content: string;
	squadId: string | null;
	status: string;
	response: string | null;
	createdAt: string;
}

export function FeedView() {
	const [items, setItems] = useState<FeedItem[]>([]);
	const [selected, setSelected] = useState<FeedItem | null>(null);
	const [filter, setFilter] = useState<'all' | 'unread'>('all');

	useEffect(() => {
		api
			.get<{ entries: FeedItem[] }>('/inbox')
			.then((d) => setItems(d.entries))
			.catch(() => {});
	}, []);

	function handleSelect(item: FeedItem) {
		setSelected(item);
		if (item.status === 'unread') {
			api
				.post(`/inbox/${item.id}/read`)
				.then(() => {
					setItems((prev) => prev.map((i) => (i.id === item.id ? { ...i, status: 'read' } : i)));
				})
				.catch(() => {});
		}
	}

	const filtered = items.filter((i) => filter === 'all' || i.status === 'unread');
	const unreadCount = items.filter((i) => i.status === 'unread').length;

	return (
		<div className="flex h-full">
			{/* List */}
			<div className="w-80 border-r border-white/[0.07] flex flex-col h-full bg-[#181818]">
				<div className="p-3 border-b border-white/[0.07]">
					<div className="flex items-center justify-between mb-2">
						<h2
							className="text-lg tracking-wide text-zinc-100"
							style={{ fontFamily: "'Bebas Neue', sans-serif" }}
						>
							Feed
						</h2>
						{unreadCount > 0 && (
							<Chip variant="default">{unreadCount}</Chip>
						)}
					</div>
					<div className="flex gap-1 p-1 rounded-xl bg-white/[0.03] border border-white/[0.07]">
						{(['all', 'unread'] as const).map((f) => (
							<button
								key={f}
								type="button"
								onClick={() => setFilter(f)}
								className={`flex-1 px-2 py-1 rounded-lg text-[11px] font-mono transition-colors ${
									filter === f
										? 'bg-white/10 text-zinc-200'
										: 'text-zinc-600 hover:text-zinc-400'
								}`}
							>
								{f === 'all' ? 'All' : 'Unread'}
							</button>
						))}
					</div>
				</div>
				<div className="flex-1 overflow-y-auto">
					{filtered.map((item) => (
						<button
							key={item.id}
							onClick={() => handleSelect(item)}
							type="button"
							className={`w-full text-left px-4 py-3 border-b border-white/[0.05] transition-colors ${
								selected?.id === item.id
									? 'bg-white/[0.06]'
									: 'hover:bg-white/[0.03]'
							} ${item.status === 'unread' ? 'border-l-2 border-l-[#E43A9C]' : ''}`}
						>
							<div className="flex items-center gap-2">
								{item.status === 'unread' ? (
									<Mail size={12} className="text-[#E43A9C] flex-shrink-0" />
								) : (
									<MailOpen size={12} className="text-zinc-700 flex-shrink-0" />
								)}
								<span className="text-[10px] text-zinc-600 font-mono uppercase">
									{item.kind}
								</span>
							</div>
							<p
								className={`text-sm mt-1 truncate ${
									item.status === 'unread' ? 'text-zinc-200 font-medium' : 'text-zinc-400'
								}`}
							>
								{item.title}
							</p>
							<p className="text-[10px] text-zinc-700 font-mono mt-0.5">
								{new Date(item.createdAt).toLocaleString()}
							</p>
						</button>
					))}
					{filtered.length === 0 && (
						<div className="flex flex-col items-center justify-center py-12">
							<Inbox size={32} className="text-zinc-800 mb-2" />
							<p className="text-[11px] font-mono text-zinc-700">
								{filter === 'unread' ? 'All caught up' : 'No items yet'}
							</p>
						</div>
					)}
				</div>
			</div>

			{/* Detail */}
			<div className="flex-1 overflow-y-auto p-6">
				{selected ? (
					<div>
						<h2 className="text-lg text-zinc-100 font-medium mb-1">{selected.title}</h2>
						<p className="text-[11px] text-zinc-600 font-mono mb-5">
							{selected.kind} · {new Date(selected.createdAt).toLocaleString()}
						</p>
						<div
							className="prose-io"
							// biome-ignore lint: markdown rendering
							dangerouslySetInnerHTML={{ __html: marked.parse(selected.content) as string }}
						/>
					</div>
				) : (
					<div className="h-full flex items-center justify-center">
						<p className="text-[11px] font-mono text-zinc-700">
							Select an item to view details
						</p>
					</div>
				)}
			</div>
		</div>
	);
}
