// web/src/components/ChatOverlay.vue
<script setup lang="ts">
import { ref, nextTick, watch } from "vue";
import { useChatStore } from "@/stores/chat";
import { useRoute } from "vue-router";
import { MessageCircle, X, Send, Square, Minimize2 } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";

const chat = useChatStore();
const route = useRoute();
const isOpen = ref(false);
const input = ref("");
const messagesContainer = ref<HTMLElement>();

// Don't show overlay on the Chat page itself
const isOnChatPage = () => route.path === "/";

function toggle() {
  if (isOnChatPage()) return;
  isOpen.value = !isOpen.value;
}

async function send() {
  const text = input.value.trim();
  if (!text || chat.isStreaming) return;
  input.value = "";
  await chat.sendMessage(text);
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    send();
  }
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
}

watch(
  () => chat.messages.map((m) => m.content),
  async () => {
    await nextTick();
    scrollToBottom();
  },
  { deep: true }
);

watch(
  () => chat.messages.length,
  async () => {
    await nextTick();
    scrollToBottom();
  }
);
</script>

<template>
  <!-- FAB button -->
  <button
    v-if="!isOpen && !isOnChatPage()"
    @click="toggle"
    class="fixed bottom-6 right-6 z-50 w-12 h-12 rounded-full btn-gradient flex items-center justify-center shadow-glow-lg hover:scale-105 transition-transform"
    title="Chat with IO"
  >
    <MessageCircle class="w-5 h-5 text-white" />
  </button>

  <!-- Chat panel -->
  <Transition
    enter-active-class="transition-all duration-200 ease-out"
    enter-from-class="opacity-0 translate-y-4 scale-95"
    enter-to-class="opacity-100 translate-y-0 scale-100"
    leave-active-class="transition-all duration-150 ease-in"
    leave-from-class="opacity-100 translate-y-0 scale-100"
    leave-to-class="opacity-0 translate-y-4 scale-95"
  >
    <div
      v-if="isOpen"
      class="fixed bottom-6 right-6 z-50 w-96 h-[500px] bg-card border border-border rounded-xl shadow-2xl flex flex-col overflow-hidden"
    >
      <!-- Header -->
      <div class="flex items-center justify-between px-4 py-3 border-b border-border bg-header">
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></div>
          <span class="text-sm font-medium">IO Assistant</span>
        </div>
        <button
          @click="isOpen = false"
          class="p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
        >
          <Minimize2 class="w-4 h-4" />
        </button>
      </div>

      <!-- Messages -->
      <div ref="messagesContainer" class="flex-1 overflow-y-auto p-3 space-y-3">
        <div v-if="chat.messages.length === 0" class="flex items-center justify-center h-full">
          <p class="text-xs text-muted-foreground">Send a message to chat with IO</p>
        </div>

        <div
          v-for="msg in chat.messages"
          :key="msg.id"
          class="flex"
          :class="msg.role === 'user' ? 'justify-end' : 'justify-start'"
        >
          <div
            class="max-w-[80%] rounded-lg px-3 py-2 text-xs"
            :class="
              msg.role === 'user'
                ? 'bg-primary text-primary-foreground'
                : 'bg-secondary text-foreground'
            "
          >
            <MarkdownContent v-if="msg.content" :content="msg.content" :class="msg.role === 'user' ? 'prose-invert' : ''" />
            <span v-else class="text-muted-foreground">...</span>
            <div
              v-if="msg.streaming"
              class="inline-block w-1.5 h-3 bg-current animate-pulse ml-1"
            ></div>
          </div>
        </div>
      </div>

      <!-- Input -->
      <div class="border-t border-border p-3">
        <div class="flex gap-2 items-end">
          <textarea
            v-model="input"
            @keydown="handleKeydown"
            placeholder="Message IO..."
            rows="1"
            class="flex-1 resize-none rounded-md border border-input bg-input px-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-ring min-h-[36px] max-h-[80px]"
          ></textarea>
          <button
            @click="send"
            :disabled="!input.trim() || chat.isStreaming"
            class="rounded-md bg-primary text-primary-foreground p-2 hover:bg-primary/90 disabled:opacity-50 transition-colors"
          >
            <Send v-if="!chat.isStreaming" class="w-3.5 h-3.5" />
            <Square v-else class="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>
  </Transition>
</template>

// packages/web/src/components/ChatOverlay.tsx
import { IoMark } from '@/components/ui/io-mark';
import { useChat } from '@/hooks/use-chat';
import { MessageCircle, Paperclip, Send, Square, X } from 'lucide-react';
import { marked } from 'marked';
import {
	type ChangeEvent,
	type KeyboardEvent,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
} from 'react';

export function ChatOverlay() {
	const [open, setOpen] = useState(false);
	const [input, setInput] = useState('');
	const [selectedFile, setSelectedFile] = useState<File | null>(null);
	const messagesRef = useRef<HTMLDivElement>(null);
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);

	const { messages, streaming, isStreaming, connected, sendChatMessage, addUserMessage, uploadAttachment } = useChat();

	const recentMessages = useMemo(() => messages.slice(-10), [messages]);

	useLayoutEffect(() => {
		const container = messagesRef.current;
		if (container) {
			container.scrollTop = container.scrollHeight;
		}
	}, [recentMessages, streaming, isStreaming, open]);

	async function handleSend() {
		const text = input.trim();
		if ((!text && !selectedFile) || isStreaming) return;

		const messageId = crypto.randomUUID();
		const attachmentName = selectedFile?.name;
		const outboundContent = [text, attachmentName ? `Attachment: ${attachmentName}` : '']
			.filter(Boolean)
			.join('\n\n');

		addUserMessage({
			id: messageId,
			role: 'user',
			content: text,
			timestamp: new Date().toISOString(),
			attachmentName,
		});
		setInput('');
		setSelectedFile(null);
		if (fileInputRef.current) fileInputRef.current.value = '';
		if (textareaRef.current) textareaRef.current.style.height = 'auto';

		try {
			if (selectedFile) {
				await uploadAttachment(selectedFile, messageId);
			}
			sendChatMessage(outboundContent);
			setOpen(true);
		} catch {
			// handled by context
		}
	}

	function handleInput(event: ChangeEvent<HTMLTextAreaElement>) {
		setInput(event.target.value);
		if (textareaRef.current) {
			textareaRef.current.style.height = 'auto';
			textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 96)}px`;
		}
	}

	function handleKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			void handleSend();
		}
	}

	return (
		<div className="fixed bottom-5 right-5 z-50 flex flex-col items-end gap-3">
			{open && (
				<div className="w-[340px] h-[460px] rounded-2xl border border-white/[0.09] shadow-2xl overflow-hidden flex flex-col" style={{ background: '#1c1c1c' }}>
					<div
						className="flex items-center justify-between px-4 py-3 border-b border-white/[0.07] flex-shrink-0"
						style={{ background: 'linear-gradient(135deg, rgba(216,51,51,0.18) 0%, rgba(240,65,255,0.10) 100%)' }}
					>
						<div className="flex items-center gap-2.5">
							<IoMark height={20} />
							<span className="text-xl text-white tracking-wider leading-none" style={{ fontFamily: "'Bebas Neue', sans-serif" }}>IO</span>
							<span className="text-[10px] font-mono text-zinc-600 mt-0.5">quick chat</span>
						</div>
						<button
							type="button"
							onClick={() => setOpen(false)}
							className="p-1 rounded-lg hover:bg-white/[0.07] text-zinc-600 hover:text-zinc-300 transition-colors cursor-pointer"
						>
							<X className="w-3.5 h-3.5" />
						</button>
					</div>

					<div ref={messagesRef} className="flex-1 overflow-y-auto p-3 space-y-2">
						{recentMessages.length === 0 && !isStreaming ? (
							<div className="h-full flex items-center justify-center text-center px-6">
								<p className="text-xs text-zinc-500">Ask IO anything without leaving this page.</p>
							</div>
						) : (
							recentMessages.map((message) => (
								<div
									key={message.id}
									className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
									title={message.timestamp}
								>
									<div className={`max-w-[85%] ${message.role === 'user' ? 'ml-8' : 'mr-8'}`}>
										{message.attachmentName && (
											<div className="mb-1 rounded-xl border border-white/[0.08] bg-[#1e1e1e] px-3 py-2 text-[11px] font-mono text-zinc-400">
												{message.attachmentName}
											</div>
										)}
										{message.content && (
											<div
												className={message.role === 'user' ? 'bg-gradient-to-br from-[#E43A9C] to-[#D83333] rounded-xl px-3 py-2 text-xs text-white whitespace-pre-wrap' : 'bg-[#2a2a2a] rounded-xl px-3 py-2 text-xs text-zinc-200'}
											>
												{message.role === 'user' ? (
													message.content
												) : (
													<div
														className="prose-io [&_*]:text-xs"
														// biome-ignore lint: markdown rendering
														dangerouslySetInnerHTML={{ __html: marked.parse(message.content) as string }}
													/>
												)}
											</div>
										)}
									</div>
								</div>
							))
						)}

						{isStreaming && (
							<div className="flex justify-start">
								<div className="max-w-[85%] mr-8 bg-[#2a2a2a] rounded-xl px-3 py-2 text-xs text-zinc-200">
									{streaming ? (
										<div
											className="prose-io [&_*]:text-xs"
											// biome-ignore lint: streaming markdown
											dangerouslySetInnerHTML={{ __html: marked.parse(streaming) as string }}
										/>
									) : (
										<div className="flex items-center gap-1.5 py-1">
											{[0, 120, 240].map((delay) => (
												<span
													key={delay}
													className="w-1.5 h-1.5 rounded-full bg-[#E43A9C] animate-bounce"
													style={{ animationDelay: `${delay}ms` }}
												/>
											))}
										</div>
									)}
								</div>
							</div>
						)}
					</div>

					<div className="p-2.5 border-t border-white/[0.06]">
						<div className="bg-[#252525] border border-white/[0.08] rounded-xl overflow-hidden transition-colors focus-within:border-[#E43A9C]/30">
							<input
								ref={fileInputRef}
								type="file"
								className="hidden"
								onChange={(event) => setSelectedFile(event.target.files?.[0] ?? null)}
							/>
							{selectedFile && (
								<div className="px-3 pt-2 text-[10px] font-mono text-zinc-400">Attached: {selectedFile.name}</div>
							)}
							<div className="flex items-center gap-1.5 px-2.5 py-2">
								<button
									type="button"
									onClick={() => fileInputRef.current?.click()}
									className="p-1 rounded-lg text-zinc-600 hover:text-zinc-300 hover:bg-white/[0.06] transition-colors flex-shrink-0 cursor-pointer"
								>
									<Paperclip className="w-3.5 h-3.5" />
								</button>
								<textarea
									ref={textareaRef}
									value={input}
									onChange={handleInput}
									onKeyDown={handleKeyDown}
									placeholder="Message IO…"
									rows={1}
									className="flex-1 bg-transparent text-xs text-zinc-200 placeholder:text-zinc-700 resize-none focus:outline-none leading-relaxed"
									style={{ minHeight: '18px', maxHeight: '96px', fontFamily: 'Inter, sans-serif' }}
								/>
								<button
									type="button"
									onClick={() => void handleSend()}
									disabled={(!input.trim() && !selectedFile) || (!connected && !isStreaming)}
									className="p-1.5 rounded-lg text-white disabled:opacity-25 disabled:cursor-not-allowed transition-opacity hover:opacity-90 flex-shrink-0 cursor-pointer"
									style={{ background: 'linear-gradient(135deg, #D83333, #E43A9C)' }}
								>
									{isStreaming ? <Square className="w-3 h-3" /> : <Send className="w-3 h-3" />}
								</button>
							</div>
						</div>
					</div>
				</div>
			)}

			<button
				type="button"
				onClick={() => setOpen((prev) => !prev)}
				className="w-12 h-12 rounded-full primary-btn shadow-lg text-white flex items-center justify-center hover:opacity-95 transition-opacity"
				aria-label={open ? 'Close quick chat' : 'Open quick chat'}
			>
				<MessageCircle className="w-5 h-5" />
			</button>
		</div>
	);
}
