// web/src/App.vue
<script setup lang="ts">
import AppSidebar from "@/components/AppSidebar.vue";
import AppHeader from "@/components/AppHeader.vue";
import ChatOverlay from "@/components/ChatOverlay.vue";
import { useAuthStore } from "@/stores/auth";
import { computed } from "vue";
import { useRoute } from "vue-router";

const auth = useAuthStore();
const route = useRoute();
const showChrome = computed(() => auth.isAuthenticated && route.name !== "login");
</script>

<template>
  <div class="flex h-screen overflow-hidden">
    <AppSidebar v-if="showChrome" />
    <div class="flex-1 flex flex-col overflow-hidden">
      <AppHeader v-if="showChrome" />
      <main class="flex-1 overflow-auto">
        <router-view />
      </main>
    </div>
    <ChatOverlay v-if="showChrome" />
  </div>
</template>

// web/src/App.tsx
import { useEffect } from "react";
import { useLocation } from "react-router";
import { useAuthStore } from "@/stores/auth";
import { AppSidebar } from "@/components/AppSidebar";
import { AppHeader } from "@/components/AppHeader";
import { ChatOverlay } from "@/components/ChatOverlay";
import { AppRoutes } from "@/routes";

export function App() {
  const token = useAuthStore((s) => s.token);
  const initAuthListener = useAuthStore((s) => s.initAuthListener);
  const refreshToken = useAuthStore((s) => s.refreshToken);
  const location = useLocation();

  const showChrome = !!token && location.pathname !== "/login";

  useEffect(() => {
    initAuthListener();
    if (token) {
      refreshToken();
    }
  }, []);

  return (
    <div className="flex h-screen overflow-hidden">
      {showChrome && <AppSidebar />}
      <div className="flex-1 flex flex-col overflow-hidden">
        {showChrome && <AppHeader />}
        <main className="flex-1 overflow-auto">
          <AppRoutes />
        </main>
      </div>
      {showChrome && <ChatOverlay />}
    </div>
  );
}
