// web/src/components/AppHeader.tsx
import { useNavigate } from "react-router";
import { useAuthStore } from "@/stores/auth";
import { Inbox, LogOut, User } from "lucide-react";

export function AppHeader() {
  const email = useAuthStore((s) => s.email);
  const logout = useAuthStore((s) => s.logout);
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate("/login");
  };

  return (
    <header className="flex items-center justify-end gap-4 px-6 py-3 bg-header border-b border-border">
      <button
        onClick={() => navigate("/feed")}
        className="text-muted-foreground hover:text-foreground transition-colors"
        title="Inbox"
      >
        <Inbox size={20} />
      </button>
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <User size={16} />
        <span>{email ?? "User"}</span>
      </div>
      <button
        onClick={handleLogout}
        className="text-muted-foreground hover:text-foreground transition-colors"
        title="Logout"
      >
        <LogOut size={18} />
      </button>
    </header>
  );
}

// web/src/components/AppHeader.vue
<script setup lang="ts">
import { useAuthStore } from "@/stores/auth";
import { useRouter } from "vue-router";
import { LogOut, Inbox, User } from "lucide-vue-next";

const auth = useAuthStore();
const router = useRouter();

async function logout() {
  await auth.logout();
  router.push("/login");
}
</script>

<template>
  <header class="h-12 border-b border-border bg-header flex items-center justify-between px-4 shrink-0">
    <div></div>
    <div class="flex items-center gap-2">
      <router-link
        to="/feed"
        class="p-2 rounded-md hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
        title="Inbox"
      >
        <Inbox class="w-4 h-4" />
      </router-link>
      <div class="w-7 h-7 rounded-full bg-secondary flex items-center justify-center" title="User">
        <User class="w-3.5 h-3.5 text-muted-foreground" />
      </div>
      <button
        @click="logout"
        class="p-2 rounded-md hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
        title="Sign out"
      >
        <LogOut class="w-4 h-4" />
      </button>
    </div>
  </header>
</template>
