// web/src/components/AppSidebar.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useRoute } from "vue-router";
import LogoIcon from "@/components/LogoIcon.vue";
import {
  MessageSquare,
  Users,
  Activity,
  Inbox,
  Puzzle,
  Server,
  Clock,
  BookOpen,
  History,
  Settings,
  BarChart3,
  ClipboardList,
  PanelLeftClose,
  PanelLeftOpen,
  Github,
} from "lucide-vue-next";

const route = useRoute();

const collapsed = ref(false);

const navItems = [
  { name: "Chat", icon: MessageSquare, path: "/" },
  { name: "History", icon: History, path: "/history" },
  { name: "Squads", icon: Users, path: "/squads" },
  { name: "Health", icon: Activity, path: "/squads/health" },
  { name: "Usage", icon: BarChart3, path: "/usage" },
  { name: "Audit Log", icon: ClipboardList, path: "/audit-log" },
  { name: "Skills", icon: Puzzle, path: "/skills" },
  { name: "MCP Servers", icon: Server, path: "/mcp" },
  { name: "Schedules", icon: Clock, path: "/schedules" },
  { name: "Wiki", icon: BookOpen, path: "/wiki" },
];

const footerItems = [
  { name: "Chat", icon: MessageSquare, path: "/" },
  { name: "Feed", icon: Inbox, path: "/feed" },
  { name: "Settings", icon: Settings, path: "/settings" },
];

const APP_VERSION = __APP_VERSION__;
const REPO_URL = "https://github.com/michaeljolley/io";

// Find the best (longest prefix) matching nav path for the current route.
const activeNavPath = computed(() => {
  let bestPath = "";
  const allItems = [...navItems, ...footerItems];
  for (const item of allItems) {
    const p = item.path;
    const matches =
      p === "/"
        ? route.path === "/"
        : route.path === p || route.path.startsWith(p + "/");
    if (matches && p.length > bestPath.length) {
      bestPath = p;
    }
  }
  return bestPath;
});

function toggleCollapse() {
  collapsed.value = !collapsed.value;
}
</script>

<template>
  <aside
    :class="[
      'border-r border-border bg-sidebar flex flex-col h-full shrink-0 transition-all duration-200',
      collapsed ? 'w-16' : 'w-56',
    ]"
  >
    <!-- Logo + Collapse toggle -->
    <div class="p-3 border-b border-border flex items-center" :class="collapsed ? 'justify-center' : 'justify-between'">
      <router-link to="/" class="flex items-center gap-2" :class="collapsed ? 'justify-center' : ''">
        <LogoIcon :size="24" />
        <h1 v-if="!collapsed" class="text-base font-bold tracking-tight bg-gradient-brand bg-clip-text text-transparent">IO</h1>
      </router-link>
      <button
        @click="toggleCollapse"
        class="p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
        :title="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
        v-if="!collapsed"
      >
        <PanelLeftClose class="w-4 h-4" />
      </button>
    </div>

    <!-- Expand button when collapsed -->
    <button
      v-if="collapsed"
      @click="toggleCollapse"
      class="mx-auto mt-2 p-1.5 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
      title="Expand sidebar"
    >
      <PanelLeftOpen class="w-4 h-4" />
    </button>

    <!-- Navigation -->
    <nav class="flex-1 p-2 space-y-0.5 overflow-y-auto">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 rounded-md text-sm transition-colors"
        :class="[
          collapsed ? 'justify-center px-2 py-2' : 'px-3 py-2',
          activeNavPath === item.path
            ? 'bg-primary/10 text-primary font-medium'
            : 'text-muted-foreground hover:bg-accent hover:text-foreground',
        ]"
        :title="collapsed ? item.name : undefined"
      >
        <component :is="item.icon" class="w-4 h-4 shrink-0" />
        <span v-if="!collapsed">{{ item.name }}</span>
      </router-link>
    </nav>

    <!-- Footer -->
    <div class="border-t border-border p-2 space-y-0.5">
      <router-link
        v-for="item in footerItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 rounded-md text-sm transition-colors"
        :class="[
          collapsed ? 'justify-center px-2 py-2' : 'px-3 py-2',
          activeNavPath === item.path
            ? 'bg-primary/10 text-primary font-medium'
            : 'text-muted-foreground hover:bg-accent hover:text-foreground',
        ]"
        :title="collapsed ? item.name : undefined"
      >
        <component :is="item.icon" class="w-4 h-4 shrink-0" />
        <span v-if="!collapsed">{{ item.name }}</span>
      </router-link>

      <!-- Version + GitHub -->
      <div
        class="flex items-center pt-2 mt-2 border-t border-border"
        :class="collapsed ? 'justify-center' : 'justify-between px-3'"
      >
        <a
          v-if="!collapsed"
          :href="`${REPO_URL}/releases/tag/v${APP_VERSION}`"
          target="_blank"
          class="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
          title="Release notes"
        >
          v{{ APP_VERSION }}
        </a>
        <a
          :href="REPO_URL"
          target="_blank"
          class="p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
          title="GitHub repository"
        >
          <Github class="w-3.5 h-3.5" />
        </a>
      </div>
    </div>
  </aside>
</template>

// web/src/components/AppSidebar.tsx
import { useState } from "react";
import { NavLink, useLocation } from "react-router";
import { LogoIcon } from "./LogoIcon";
import {
  MessageSquare,
  Inbox,
  Users,
  Zap,
  Server,
  Clock,
  History,
  BookOpen,
  BarChart3,
  Shield,
  Settings,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
} from "lucide-react";

const navItems = [
  { path: "/", icon: MessageSquare, label: "Chat" },
  { path: "/feed", icon: Inbox, label: "Feed" },
  { path: "/squads", icon: Users, label: "Squads" },
  { path: "/skills", icon: Zap, label: "Skills" },
  { path: "/mcp", icon: Server, label: "MCP" },
  { path: "/schedules", icon: Clock, label: "Schedules" },
  { path: "/history", icon: History, label: "History" },
  { path: "/wiki", icon: BookOpen, label: "Wiki" },
  { path: "/usage", icon: BarChart3, label: "Usage" },
  { path: "/audit-log", icon: Shield, label: "Audit Log" },
  { path: "/settings", icon: Settings, label: "Settings" },
];

export function AppSidebar() {
  const [collapsed, setCollapsed] = useState(false);
  const location = useLocation();

  return (
    <aside
      className={`flex flex-col bg-sidebar border-r border-border transition-all duration-200 ${
        collapsed ? "w-16" : "w-56"
      }`}
    >
      {/* Logo */}
      <div className="flex items-center gap-2 px-4 py-4 border-b border-border">
        <LogoIcon size={28} />
        {!collapsed && <span className="font-bold text-lg text-gradient-brand">IO</span>}
      </div>

      {/* Nav */}
      <nav className="flex-1 overflow-y-auto py-2">
        {navItems.map(({ path, icon: Icon, label }) => {
          const isActive = path === "/" ? location.pathname === "/" : location.pathname.startsWith(path);
          return (
            <NavLink
              key={path}
              to={path}
              className={`flex items-center gap-3 px-4 py-2.5 mx-2 rounded-md transition-colors ${
                isActive
                  ? "bg-accent text-accent-foreground"
                  : "text-muted-foreground hover:bg-accent/50 hover:text-foreground"
              }`}
            >
              <Icon size={20} />
              {!collapsed && <span className="text-sm">{label}</span>}
            </NavLink>
          );
        })}
      </nav>

      {/* Footer */}
      <div className="border-t border-border p-2">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="flex items-center gap-2 px-2 py-1.5 w-full rounded-md text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-colors"
        >
          {collapsed ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}
          {!collapsed && <span className="text-xs">Collapse</span>}
        </button>
        {!collapsed && (
          <div className="flex items-center justify-between px-2 mt-2">
            <span className="text-xs text-muted-foreground">v{__APP_VERSION__}</span>
            <a
              href="https://github.com/michaeljolley/io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-foreground"
            >
              <ExternalLink size={14} />
            </a>
          </div>
        )}
      </div>
    </aside>
  );
}
