// web/src/components/MarkdownContent.vue
<script setup lang="ts">
import { computed } from "vue";
import { marked } from "marked";

const props = defineProps<{ content: string }>();

const rendered = computed(() => {
  if (!props.content) return "";
  return marked.parse(props.content, { async: false }) as string;
});
</script>

<template>
  <div class="prose prose-sm dark:prose-invert max-w-none" v-html="rendered"></div>
</template>

// web/src/components/MarkdownContent.tsx
import { useMemo } from "react";
import { marked } from "marked";

interface MarkdownContentProps {
  content: string;
  className?: string;
}

export function MarkdownContent({ content, className = "" }: MarkdownContentProps) {
  const html = useMemo(() => {
    const renderer = new marked.Renderer();
    renderer.link = ({ href, title, text }) => {
      return `<a href="${href}" title="${title ?? ""}" target="_blank" rel="noopener noreferrer">${text}</a>`;
    };
    return marked(content, { renderer, async: false }) as string;
  }, [content]);

  return (
    <div
      className={`prose prose-invert max-w-none ${className}`}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
